### PR TITLE
Azure pipeline for linux and macos and fix osx build

### PR DESCRIPTION
**Pull request by sonic182**
Added azure pipeline for linux and macos builds. I think would be nice to add windows build too.

I'm still having a issue building with Mac Os for missing files, I expect help with this pr
Error in azure: 
`/Users/vsts/agent/2.155.1/work/1/s/reicast/apple/emulator-osx/build/reicast-osx.build/Release/reicast-osx.build/Script-AE60BDA5222B7E8000FA8A5B.sh: line 2: /Users/vsts/agent/2.155.1/work/1/s/reicast/apple/emulator-osx/../../../core/version.h: No such file or directory
`

My latest azure builds: https://dev.azure.com/johander-182/reicast/_build?definitionId=2

### CODE REVIEW

**Comment by skmp** [comment]
I still plan to merge this one

**Comment by sonic182** [comment]
Ok, should I reopen this pr?

Best regards
Johanderson

**Comment by skmp** [comment]
yes please :)

**Comment by sonic182** [comment]
Oh, I removed my fork, I hope I keep the code in my Mac at home, I'll let you know here later

**Comment by skmp** [comment]
@sonic182 any updates on this?

**Comment by sonic182** [comment]
I reopened it here https://github.com/reicast/reicast-emulator/pull/1826 @skmp

**Pull request closed without merging**
