### PR TITLE
GDI: Reset skipws-flag

### LINKED ISSUE #1006: Linux: cannot open gdi files that contain special characters
Linux reicast fails to open gdi files if any of the file names contained within contain special characters such as parentheses or commas.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41666896-linux-cannot-open-gdi-files-that-contain-special-characters?utm_campaign=plugin&utm_content=tracker%2F500311&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500311&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by baka0815**
When loading gdi files with special characters, the skipws-flag is now reset properly.
Previously it was not reset and so there was a problem reading the stream (``TRACK``, etc. were not set for the following lines).

GDI-file:
````
3
1 0 4 2352 "track (0,1).bin" 0
2 450 0 2352 track02.raw 0
3 45000 4 2352 track03.bin 0
````

That was the output I got:
````
GDI : 3 tracks
file[1] "track (0,1).bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:0
file[0] "": FAD:0, CTRL:0, SSIZE:0, OFFSET:0
file[0] "": FAD:0, CTRL:0, SSIZE:0, OFFSET:0
````

After the change this is the output:
````
GDI : 3 tracks
file[1] "track (0,1).bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:0
file[2] "track02.raw": FAD:450, CTRL:0, SSIZE:2352, OFFSET:0
file[3] "track03.bin": FAD:45000, CTRL:4, SSIZE:2352, OFFSET:0
````
This fixes #1006.

This was taken from from #1190.

### CODE REVIEW

**Comment by LoungeKatt** [comment]
https://github.com/baka0815/reicast-emulator/blob/41ee5707a827ed94327b4d18551bcadc3f06c524/core/imgread/gdi.cpp#L117 should also be moved above https://github.com/baka0815/reicast-emulator/blob/41ee5707a827ed94327b4d18551bcadc3f06c524/core/imgread/gdi.cpp#L116 (for consistency)

**Comment by skmp** [comment]
Can you add the test GDIs `https://github.com/reicast/reicast-emulator/tree/master/tests/files/test_gdis`? Otherwise, looks good to me. It's nice to see this kind of silly bugs getting fixed :3

**Comment by baka0815** [comment]
@LoungeKatt ok, I'll change that like in the code you quoted from RA.

@skmp Do you mean the gdi file I quoted above? Are there any guidelines on naming the file?

**Comment by skmp** [comment]
Not really- just make up something sensible that fits with the existing pattern.

**Comment by baka0815** [comment]
Ok, I added the test case and surrounded the for-loop with skipws/noskipws.

**Pull request merged**
