### PR TITLE
Update project for #755 and fix warnings

### PR DESCRIPTION
**Pull request by LoungeKatt**
@skmp can you verify fixing these warnings doesn't break anything for you?

Tested Android and iOS and both appear good, but Xcode kept yelling.

@Holzhaus I should be asking you, too, since you've been doing warnings recently. Still good?

### CODE REVIEW

**Comment by skmp** [comment]
You 150% don't want %s there. %p would do I think

**Comment by LoungeKatt** [comment]
Blame Xcode. It told me it had to be s. It was really convincing about it, too.

**Comment by Holzhaus** [comment]
Looks good to me.

**Comment by skmp** [comment]
Okay, i get a random crash on iOS. DEbugging

**Comment by LoungeKatt** [comment]
The EXC_BAD_ACCESS code 2?

**Comment by skmp** [comment]
I did some more fixing, I say we close this and resume on #766!

**Comment by LoungeKatt** [comment]
Sounds like a plan

**Pull request closed without merging**
