### PR TITLE
Cleanup and rework to start fixing issues ;)

### PR DESCRIPTION
**Pull request by LoungeKatt**

### CODE REVIEW

**Comment by skmp** [comment]
Mnn

**Comment by skmp** [comment]
Mnn

**Comment by LoungeKatt** [comment]
Yeah, there is a lot to do...

**Comment by skmp** [comment]
Alright! Back on my laptop :3

**Comment by skmp** [comment]
(looks like all changes on the android side of things, so I guess it's your area @LoungeKatt )

**Comment by skmp** [comment]
from CI

```
[javac] Compiling 31 source files to /home/travis/build/reicast/reicast-emulator/shell/android/bin/classes
    [javac] /home/travis/build/reicast/reicast-emulator/shell/android/src/com/reicast/emulator/AboutFragment.java:42: error: cannot find symbol
    [javac] 	SlidingDrawer slidingGithub;
    [javac] 	^
    [javac]   symbol:   class SlidingDrawer
    [javac]   location: class AboutFragment
    [javac] /home/travis/build/reicast/reicast-emulator/shell/android/src/com/reicast/emulator/AboutFragment.java:93: error: cannot find symbol
    [javac] 		slidingGithub = (SlidingDrawer) getView().findViewById(
    [javac] 		                 ^
    [javac]   symbol:   class SlidingDrawer
    [javac]   location: class AboutFragment
    [javac] /home/travis/build/reicast/reicast-emulator/shell/android/src/com/reicast/emulator/AboutFragment.java:95: error: cannot find symbol
    [javac] 		slidingGithub.setOnDrawerOpenListener(new OnDrawerOpenListener() {
    [javac] 		                                          ^
    [javac]   symbol:   class OnDrawerOpenListener
    [javac]   location: class AboutFragment
    [javac] /home/travis/build/reicast/reicast-emulator/shell/android/src/com/reicast/emulator/FileBrowser.java:209: error: method showToastMessage in class MainActivity cannot be applied to given types;
    [javac] 			MainActivity.showToastMessage(getActivity(), 
    [javac] 			            ^
    [javac]   required: Context,String,int,int
    [javac]   found: FragmentActivity,String,int
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /home/travis/build/reicast/reicast-emulator/shell/android/src/com/reicast/emulator/FileBrowser.java:393: error: method showToastMessage in class MainActivity cannot be applied to given types;
    [javac] 								MainActivity.showToastMessage(getActivity(), 
    [javac] 								            ^
    [javac]   required: Context,String,int,int
    [javac]   found: FragmentActivity,String,int
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /home/travis/build/reicast/reicast-emulator/shell/android/src/com/reicast/emulator/FileBrowser.java:490: error: method showToastMessage in class MainActivity cannot be applied to given types;
    [javac] 										MainActivity.showToastMessage(getActivity(), 
    [javac] 										            ^
    [javac]   required: Context,String,int,int
    [javac]   found: FragmentActivity,String,int
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /home/travis/build/reicast/reicast-emulator/shell/android/src/com/reicast/emulator/emu/GL2JNIView.java:694: error: method showToastMessage in class MainActivity cannot be applied to given types;
    [javac] 					MainActivity.showToastMessage(context, msg, Toast.LENGTH_SHORT);
    [javac] 					            ^
    [javac]   required: Context,String,int,int
    [javac]   found: Context,String,int
    [javac]   reason: actual and formal argument lists differ in length
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 7 errors
```

**Comment by LoungeKatt** [comment]
Yeah, it's still a mess. There are still a few changes before this is ready.

**Comment by LoungeKatt** [comment]
@skmp Any reason why bitrise hates... everything?

**Comment by skmp** [comment]
The ios singing key I used for it has expired. I need to get a new one

**Comment by sabula310** [comment]
start all over coding  it have a error

**Comment by LoungeKatt** [comment]
@sabula310 No, bitrise has an issue.

**Pull request merged**
