### PR TITLE
[WIP] Some inital work for libretro

### PR DESCRIPTION
**Pull request by Holzhaus**
This doesn't contain anything interesting yet, but if you want to, you can leave comments on how stuff should be done :D

### CODE REVIEW

**Comment by Alcaro** [comment]
Some of that looks familiar... as if you copypasted it from Gambatte or something.

>+	bool retro_load_game_special(unsigned game_type, const struct retro_game_info *info, size_t num_info)
>+	{
>+		return false; //TODO (?)
>+	}

Rarely needed. It's fine to leave it empty.

>+	void *retro_get_memory_data(unsigned type)
>+	{
>+		return 0; //TODO
>+	}

You used 0 here, but you used a NULL in dc_init(). Is that intentional?

>-    USE_X11 := 1
>+    #USE_X11 := 1

Let's... let's not break standalone builds, okay? Better to wrap it in an ifdef LIBRETRO or something.

If you've got any other questions, post them here, or join #libretro on Freenode.

Also pinging issue #630.

**Comment by Holzhaus** [comment]
I usually fix the makefiles when stuff is in a mergeable state (so that I can easily recompile during the coding phase...yeah. I'm THAT lazy).

The main roadblock I'm hitting: dc_run loops forever, but libretro calls it per frame (if I understand it correctly).

**Comment by Alcaro** [comment]
That is correct.

Grepping in the source suggests that defining TARGET_BOUNDED_EXECUTION makes it return every 10000 opcodes. If you prefer controlling the returns yourself (you should, otherwise you'll need a weird loop in retro_run()), call sh4_cpu.Stop() at some suitable point (the video callback, for example).

If that doesn't work, we could fiddle with [libco](https://github.com/libretro/bsnes-libretro/tree/libretro/libco) (a coroutine library for C/C++), but it's a pretty ugly mechanism, so try sh4_cpu.Stop() first. Strange how there's no dc_stop() that forwards to that one.

**Comment by skmp** [comment]
The codebase is not meant to be run like that. The TARGET_BOUNDED_EXECUTION toggle will make it in a very "hacky" way, and it's not a stable way to do it yet. Dreamcast is more "modern" than other consoles, and has no fixed video output. Running "one frame" is complicated. Each frame might last a different amount of time, or there might be no new data rendered, or the video might even be "off"

**Comment by skmp** [comment]
For a quick port I'd say we go the threaded way (so run_frame actually waits for a frame, then renders). That's how android and ios work for now. This will make pausing etc broken, which is I guess another issue that needs to be addressed.

The current JIT implementations don't support exiting or pausing, afair.

**Comment by twinaphex** [comment]
Might as well close this.

**Comment by Holzhaus** [comment]
@twinaphex Any plans to merge the existing libretro implementation upstream?

**Comment by twinaphex** [comment]
Nope, all bridges were burnt after I was booted out of this 'team'. And given the lack of willingness to fix crucial bugs in Reicast and priorities being elsewhere, I think it's best if I just stick to my own fork.

**Comment by twinaphex** [comment]
I was the only one in over two years who even sent any commits his way that fixed game compatibility issues anyway instead of mere frontend tinkering, so yeah, he can have fun with the rest of what remains here. I'm not looking back anymore and will do the same as what I did in mupen64plus' case. When upstream stops making sense and has their head stuck between its ass, I view it as a lost cause and just them wasting my time/stifling the progress I could be making. I am starting to view this as another one of these examples.

**Comment by LoungeKatt** [comment]
@twinaphex It is clear you have an issue with the creator of the project and that is your business. There is no need to drag the entire team into it with an egotistical claim that you were the only one to contribute any real work, especially having said that Android, where the work was being done, is part of the project with which you were unfamiliar. Thanks.

**Comment by twinaphex** [comment]
@LoungeKatt Oh I see, some frontend code pusher feels the need to add his final two cents in. 

With all due respect, dude, but I don't need you to add your last two cents in, especially when you don't even know what you are talking about.

RetroArch Android has existed for longer than you have probably been coding. Please keep your mouth shut if you don't know what you are talking about.

And with that said, I am out. I will decide for myself exactly who I drag into what By all means self-identify with this little project all you want and the progress (or lack thereof) it has made for years, but you will no longer be seeing any pull requests from me unless @skmp starts humbling himself and actually starts giving a shit again about improving core emulation. Or hell, at least fix the regressions you caused in nullDC and at least bring it up to nullDC's level for god's sake. That is better than leaving it perpetually broken for years and playing silly games with your endusers.

**Comment by LoungeKatt** [comment]
@twinaphex "As for Reicast for Android, I'll try looking into it. I just never got to it before." (#947).
Rather than taking a polite request not to be so obnoxious, you decided to run your mouth again. I have little concern about your opinion of my contribution to this project. The reason is not the progress in RetroArch or your personal contribution to this project. The reason is that the best you have to say is some insulting, egotistical trash about being some sort of messiah. You, as a person, do not fit in here because you, as a person, are not good enough. It has little to do with code.

**Comment by LoungeKatt** [comment]
@Holzhaus There are no plans, but all comments by the author have been removed to avoid having the repository dragged down by immature, offensive, and egotistical ramblings. 

This post is only meant for archival purposes.

**Pull request closed without merging**
