### PR TITLE
iOS rebuild to support file list and controllers

### PR DESCRIPTION
**Pull request by LoungeKatt**
This is a WIP, but the current progress does work

### CODE REVIEW

**Comment by mk8itra1n** [comment]
Looks like this will be like the alpha version of the android version. Sonic Adventure here I come🎉

**Comment by LoungeKatt** [comment]
If by that you mean doesn't have sound, sure. As for the rest, it's going to be fairly close to the earlier builds of reicast until it's cleaned up.

**Comment by mk8itra1n** [comment]
Ah okay. I've seen the android version and it's really good even though it's an alpha. I'm sure you'll do a great job on the iOS version. Can't wait for the sound support. Any ETA when this new build will be pushed to github? It seems you are making good progress @loungekatt. I apologize if im lighting you up with questions. I'm just curious for progress😂👍

**Comment by Holzhaus** [comment]
It's done when it's done. There might always turn up some unexpected problem ;-)

**Comment by mk8itra1n** [comment]
This build really looks like an android alpha version. Can't wait for this to get pushed!!

**Comment by mk8itra1n** [comment]
I'll be keeping an eye on this checklist. With the file selector and partially working overlay progres is being made. Keep up the good work @skmp @loungekatt

**Comment by skmp** [comment]
@LoungeKatt, after a fast review this looks good (I don't know anything about UIKit, though).

**Comment by LoungeKatt** [comment]
I don't either or it'd probably be done by now :/

**Comment by LoungeKatt** [comment]
The overlay really doesn't like anything else. It's showing up but it doesn't take any form of touch input. Once that works this should be ready, though.

**Comment by rasterico** [comment]
happy to test out this build for you on my devices if you like? Got an iPad an iPhone 6 and an iMac, I know the overlay is your main priority to get this working for all configurations but as a work around is there support for MFI controllers yet?

**Comment by mk8itra1n** [comment]
I would love to test this build now that I know how to build reicast with Xcode 7. Got an iMac and iPhone 6 to test out this build as well as @rasterico👌

**Comment by pipikaka111** [comment]
I don't have Mac not enough space to Vmware it... Can someone give me a download link to a compiled version please ? Also is there mfi support?

**Comment by mk8itra1n** [comment]
Is this the current progress or is this outdated?

**Comment by LoungeKatt** [comment]
That should be current

**Comment by rasterico** [comment]
Any progress? Just thought I'd ask as everything's gone quiet, I'm holding off on updating to iOS 9 and losing my jailbreak in anticipation of Reicast dropping for iOS! :)

**Comment by mk8itra1n** [comment]
I'm trying to hold off on iOS 9 for as long as I can. I haven't heard anything since the end of August. Has there been any sort of progress at all since I was last here for the iOS version? @rasterico

**Comment by LoungeKatt** [comment]
I haven't done anything with it recently. I can't really schedule other people's events around when iOS versions and / or jailbreaks are released, so it's up to you if you choose to wait until I have time or someone else picks it up.

**Comment by rasterico** [comment]
That's cool, I haven't bothered with iOS 9 as I use other stuff such as Retroarch and mame4iOS anyway, just hadn't heard anything for a while so I thought I'd ask, I don't want to rush anyone, I just got excited when you started making progress a while back :)

**Comment by skmp** [comment]
@LoungeKatt can you rebase on top of master?

**Comment by mk8itra1n** [comment]
Glad to see you guys back to work on the iOS version. You think this may be the year Dreamcast comes to iDevices? Can't wait to put my iPhone 7 Plus to the test with this :)

**Comment by mk8itra1n** [comment]
I checked over the code and all seems fine. All 4 checks preformed passed and were successful. I sent in one approved review as github requires one approved review for automatic merging. I do have a newly jailbroken iPhone 7 Plus and access to Xcode if you need a beta tester for a new iOS build. Lemme know if you guys are interested and hopefully you guys will keep us posted on any new updates. Thx!

**Comment by blessedlonghair** [comment]
@mk8itra1n @LoungeKatt hey whats the setup process? i used xcode and everything and im sure i built it properly. i just cant get it to launch the bios or a game. does it only support .CHD? i got a newly jailbroken ipad pro 12.9 and im sure it can run correctly if i set it up right.

**Comment by mk8itra1n** [comment]
@blessedlonghair If you head over to the reicast github main page, find an issue called iOS version of Reicast and you'll find the instructions in that thread!

**Comment by LoungeKatt** [comment]
I misread the integration as AppVoyeur and thought we had some kinky compiler hiding in the closet watching changes. I never got the notification to rebase this, but at least it was a clean update. Checking it now to finally get some progress on the iOS version.

**Comment by mk8itra1n** [comment]
@LoungeKatt Good to see you back! Finally saw some commits for the iOS version back on May 5th. I'm guessing that means work has resumed for reicast for iOS? :)

**Comment by LoungeKatt** [comment]
Things are never that black and white.

**Comment by LoungeKatt** [comment]
This can be tested building the "loungekatt" branch. 
I've kept the other changes separate so this does not hold them up.

**Comment by mk8itra1n** [comment]
@LoungeKatt Glad your back working hard on the iOS port. I'll build the LoungeKatt branch and let you know how it runs on my iPhone 7 Plus. Have all the commits here been added into your branch for Reicast?

**Comment by LoungeKatt** [comment]
This was just rebased. The Android stuff was separated into the cleanup branch but they do work when combined. I just updated my Mac so I haven't gotten to compile it recently.

**Pull request merged**
