### PR TITLE
Allow configuration of maple devices

### LINKED ISSUE #919: Using evdev, can't enable multiple pads, only player 1 works
Hi,

I'm configuring the emu.cfg with evdev for 4 players. All pads are correctly configured, they work fine if I set them up for player 1. Evdevid's are fine also, i checked with /dev/input.

A few elements :
emu.cfg :

``` ini
[audio]
backend = auto
disable = 0

[config]
Debug.SerialConsoleEnabled = 0
Dreamcast.Broadcast = 4
Dreamcast.Cable = 3
Dreamcast.RTC = 1543276800
Dreamcast.Region = 3
Dynarec.Enabled = 1
Dynarec.idleskip = 1
Dynarec.unstable-opt = 0
aica.LimitFPS = 1
aica.NoBatch = 0
aica.NoSound = 0
aica.limitfps = 1
aica.nobatch = 0
aica.nosound = 0
bios.UseReios = 0
bios.usereios = 0
debug.serialconsoleenabled = 0
dreamcast.broadcast = 4
dreamcast.cable = 3
dreamcast.region = 3
dreamcast.rtc = 1543276800
dynarec.enabled = 1
dynarec.idleskip = 1
dynarec.unstable-opt = 0
pvr.MaxThreads = 3
pvr.Subdivide = 0
pvr.SynchronousRendering = 0
pvr.maxthreads = 3
pvr.rend = 0
pvr.subdivide = 0
pvr.synchronousrendering = 0
rend.UseMipmaps = 1
rend.WideScreen = 0
rend.usemipmaps = 1
rend.widescreen = 0
ta.skip = 0

[input]
evdev_device_id_1 = 3
evdev_device_id_2 = 4
evdev_device_id_3 = 5
evdev_device_id_4 = 2
evdev_mapping_1 = /recalbox/share/system/configs/reicast/controllerP1.cfg
evdev_mapping_2 = /recalbox/share/system/configs/reicast/controllerP2.cfg
evdev_mapping_3 = /recalbox/share/system/configs/reicast/controllerP3.cfg
evdev_mapping_4 = /recalbox/share/system/configs/reicast/controllerP4.cfg
joystick_device_id = -1

[reios]
ElfFile = 

[testing]
ta.HashCheckFile = 
ta.HashLogFile = 

[validate]
OpenGlChecks = 0
openglchecks = 0
```

evtest to show my ids are correct :

```
# evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:  Logitech USB Receiver
/dev/input/event1:  Logitech USB Receiver
/dev/input/event2:  Logitech Logitech RumblePad 2 USB
/dev/input/event3:  PLAYSTATION(R)3 Controller
/dev/input/event4:  PLAYSTATION(R)3 Controller
/dev/input/event5:  PLAYSTATION(R)3 Controller
```

You may wonder if my pad configurations are fine, and yes P1 = P2 = P3 = PS3 pad, P4 is the logitech one. If i set the logitech as the first player, i can check it's perfectly configured, but still only 1 player available

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33492894-using-evdev-can-t-enable-multiple-pads-only-player-1-works?utm_campaign=plugin&utm_content=tracker%2F500311&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500311&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1302: How do I get vmu's for port 2, 3, and 4?
I try renaming the vmu to something like "vmu_save_B1.bin" but that didn't do anything

### PR DESCRIPTION
**Pull request by baka0815**
This lets you configure the maple device (VMU, Microphone, PuruPuruPack) for each evdev controller.

In the configuration file of the evdev-device you can set 
````ini
[dreamcast]
maple_device1 = 1/2/3
maple_device2 = 1/2/3
````
while 1 is VMU, 2 is Microphone and 3 is PuruPuruPack. The default is VMU.

There now is ``os_SetupInput()`` for each shell to allow the setup the input devices.
The old ``mcfg_CreateDevices()`` was renamed to ``mcfg_CreateDevicesFromConfig()`` and creates the devices the same way as before (by using the config).
This is currently the way it's implemented for OSX, iOS and Windows (if I did it right).

Android currently creates one controller with 2 VMUs and additional controllers (if set) without any equipment.

Linux via evdev reads the configuration from the controller and defaults to VMU for each port of each configured controller.

This should fix #1302.
This supersedes #930 and fixes #919.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
You would probably need some form of config flag for port -> type and then you could move the creation back to "whence it came" and only set the mapping[port] -> type in the linux portion. (-> being "translated to" not C)

**Comment by baka0815** [comment]
I'm not sure, I fully understand what you mean.
I think that the maple devices are part of the controller (they are inserted intonthe controller on a real DC) and therefor hould be configured where the controls are and not somewhere else like the ``emu.cfg``.

**Comment by baka0815** [comment]
This could also fix what #930 is trying to fix.

Remove the ``mcfg_CreateDevices()`` call altogether and create the devices ``MDT_SegaController`` including maple device when creating the controls.

**Comment by AbandonedCart** [comment]
I mean not putting the device configuration in linux, only a helper function to get what device should be assigned to what port. Each platform would have some form of helper function, but the default would still be VMU (even if no helper exists).

**Comment by baka0815** [comment]
I refactored the code a bit.

I would then use an approach similar to ``os_CreateWindow()`` to setup the input in ``dc_init()``
https://github.com/reicast/reicast-emulator/blob/b2e07d0c96ef486f024d843e6bad4538b59d9d8b/core/nullDC.cpp#L131
and remove ``SetupInput()`` from the ``main.cpp`` (as that would then be ``os_SetupInput()``
https://github.com/reicast/reicast-emulator/blob/b2e07d0c96ef486f024d843e6bad4538b59d9d8b/core/linux-dist/main.cpp#L473

Is that what you had in mind?

**Comment by AbandonedCart** [comment]
Exactly. That seems general enough in the mainline and specific enough for the platform. Nice work!

**Comment by baka0815** [comment]
@AbandonedCart I updated the code and the PR comment.

Should we default to VMU on each port of each configured controller or only for controller 1 (like I implemented this on Android)?

**Comment by baka0815** [comment]
Fixed Android, Windows, iOS and OSX (hopefully).

**Comment by AbandonedCart** [comment]
You could probably leave it as an empty port, like you already did. On my real console, I only ever had the VMUs in the first controller.

**Comment by baka0815** [comment]
It may be me, but I have rumble and VMU in all 4. :D

**Comment by baka0815** [comment]
I would change the code to default to VMU for controller 1 (both devices) to be compatible to the previous behavior and None for the other controllers.

Any other comments? Something I should change/rework?

**Comment by AbandonedCart** [comment]
No functionality seems at risk of being lost, so anything else can probably be added later.

**Comment by baka0815** [comment]
@AbandonedCart ok, I'm done here then,

**Comment by skmp** [comment]
This pull request **introduces 1 alert** when merging 69961dbbebe93d5d43729a7b1a15a3538ec6eb4a into 223cd74824ab4a2dd9440eb4c9c4a0a3d1492712 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-618d386371f7ac30c9388431bcadf173266d442d)

**new alerts:**

* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by baka0815** [comment]
lgtm:
This argument should be of type 'char *' but is of type 'basic_string<char, char_traits<char>, allocator<char>>'

Can I just cast here?

**Comment by baka0815** [comment]
Ok, if all builds succeed, I'm done.

**Comment by AbandonedCart** [comment]
The web version of conflict resolution is a bit... awkward. You may want to perform a local rebase and force push over that. Not sure if it will clean itself up or not, but it doesn't warn that it plans to merge the whole repository in there to fix 4 lines.

**Comment by AbandonedCart** [comment]
I made the merge conflicts, so I resolved them and resubmitted the PR with the original commit intact. Apparently github's "resolve conflicts" option just pushes the entire master branch on top.

**Pull request closed without merging**
