### PR TITLE
cmake: Fix Linux build

### PR DESCRIPTION
**Pull request by scribam**
Bare minimum to make a successful compilation with CMake on Linux (with EGL).

### CODE REVIEW

**Comment by skmp** [comment]
Hey @scribam! Thanks for the contribution :)

I haven't had time to look into cmake so far, and it certainly needs some love.

**Review by skmp — APPROVED** [review]

**Comment by sl1pkn07** [comment]
~~~
-- Configuring done
CMake Error at CMakeLists.txt:251 (add_executable):
  Cannot find source file:

    /tmp/makepkg/sl1-reicast-emulator-git/src/reicast-emulator/core/linux/oslib/posix/threading.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:251 (add_executable):
  No SOURCES given to target: reicast


CMake Generate step failed.  Build files cannot be regenerated correctly.
~~~

**Comment by scribam** [comment]
@sl1pkn07 Do you use the `alpha` branch? Can you try to clean your CMake cache?

**Comment by sl1pkn07** [comment]
use master and is a clean environment

**Comment by scribam** [comment]
That's the issue then. The `alpha` branch is the only one with the fix.
I don't know why the `alpha` branch is the default and not `master` :thinking:

**Comment by sl1pkn07** [comment]
ok, using alpha branch build all ok

bTW nice GUI!

greetings

**Comment by skmp** [comment]
Master is the 'old' main branch. We switched to alpha/beta/stable in an
attempt to aid faster release cycles without too much breakage.

**Comment by scribam** [comment]
When do you close a GitHub issue? When the fix is merged in `alpha`?

**Comment by skmp** [comment]
Yup. Pushes to beta trigger an android beta release (10+k testers atm) so
they need to be vetted

**Pull request merged**
