### PR TITLE
Update donation section in readme

### PR DESCRIPTION
**Pull request by skmp**

### CODE REVIEW

**Comment by skmp** [comment]
@twinaphex @LoungeKatt how does this look?

**Comment by skmp** [comment]
Also @rrrh and @flyinghead

**Comment by skmp** [comment]
And @MrPsyMan, @dmiller423

**Comment by LoungeKatt** [comment]
and @skmp, don't forget @skmp

**Review by AbandonedCart — APPROVED** [review]

**Comment by twinaphex** [comment]
As long as Reicast keeps improving and commits stay opensource, I am fine with anything really.

**Comment by skmp** [comment]
@skmp is here just for the lulz

**Pull request merged**
