### PR TITLE
Audio backends cleanup

### PR DESCRIPTION
**Pull request by Holzhaus**
These commits clean up the audio backends and is an attempt to consolidate audio-specific code. This also makes it possible to have multiple audio backends compiled into reicast (e.g. ALSA & OSS on Linux). These can then be selected by the user via a config option ("backend" in the "audio" section). It *should* also be possible to reduce the number of platform-specific ifdefs with this approach.

Audio backends need to define a struct (`audiobackend_t`) that holds a pointer to it's init, push and term function and also a slug and a name as string. They then need to pass a pointer to this struct to `RegisterAudioBackend()` before `InitAudio()` is called.

For now, I defined a function (`RegisterAllAudioBackends()`) that get's called exactly once (i.e. upon first call of `InitAudio()`), where we can put `#ifdef`'d `RegisterAudioBackend()` calls into for each backend that reicast supports.

I subsequently added backends for OSS, ALSA, DirectSound, Android and PulseAudio. Please note that I wasn't able to test the DirectSound or Android backend, since I only have Linux. The DirectSound backend should work since I took most of the code from `ds_audiostream.cpp`, but I have no idea if the android backend is implemented correctly since I do not have any experience with Android programming in combination with native C/C++ code.

Although this compiles fine on my Linux x86_64, I actually had to apply commits a579466 to af64d37 from the [skmp/linux-x64](https://github.com/reicast/reicast-emulator/compare/skmp/linux-x64) branch to actually get sound at all.

Please check the individual commit messages for details.

### CODE REVIEW

**Comment by skmp** [comment]
Long month, late reviews.

This does look good. I'll get it in after #655 is done

**Comment by skmp** [comment]
hey @Holzhaus, can you take a look at #455 and add your name there if you agree? Then I can merge this ~

**Comment by Holzhaus** [comment]
[Yup.](https://github.com/reicast/reicast-emulator/issues/455#issuecomment-103088650)

**Comment by Holzhaus** [comment]
Should I rebase?

**Comment by LoungeKatt** [comment]
After you do, I will merge this (as long as nobody objects). It sounds like @skmp approved and Its been in my local copy through many tests of other changes.

**Comment by Holzhaus** [comment]
There you go. I recompiled and sound worked fine for me (on Linux x86_64), even without borrowing the commits a579466 to af64d37 from the skmp/linux-x64 branch.

**Pull request merged**
