### PR TITLE
[cmake] add EVDEV and JOYSTICK options

### PR DESCRIPTION
**Pull request by sl1pkn07**

### CODE REVIEW

**Comment by elBlanquito** [comment]
First of all, thank you so much for working on this! I'm curious: Will this fix the issues associated with #1050 ?

**Comment by sl1pkn07** [comment]
idk. this PR only add support for cmake same as Makefile doing (more or less)

**Comment by Sentiinela** [comment]
how to apply these options?

**Comment by sl1pkn07** [comment]
-DUSE_EVDEV=ON
-DUSE_JOYSTICK=ON

**Comment by Sentiinela** [comment]
~$ cmake CMakeLists.txt 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
CMake Error at CMakeLists.txt:204 (add_executable):
  add_executable called with incorrect number of arguments


CMake Error at CMakeLists.txt:205 (target_link_libraries):
  Cannot specify link libraries for target "reicast" which is not built by
  this project.


-- Configuring incomplete, errors occurred!

**Comment by sl1pkn07** [comment]
builld ok here:

~~~bash
└───╼  cmake CMakeLists.txt 
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/makepkg/reicast-emulator-git/src/reicast-emulator/shell/cmake

**Pull request merged**
