### PR TITLE
BSDFY: License headers, license spam

### PR DESCRIPTION
**Pull request by skmp**
Exercising the CLA rights, I'm changing the copyright in the parts of the source we have control over.

### CODE REVIEW

**Comment by flyinghead** [comment]
You should be ashamed of yourself.

**Comment by skmp** [comment]
@flyinghead we could have all worked together if you wanted so. Also, #455 has been around far before you got involved.

**Comment by flyinghead** [comment]
What you're doing is the precise reason why I don't want to work with you. You have absolutely no consideration or even respect for other people's work. And seeing how many people contribute to reicast these days, it seems I'm not alone to think this way.

Rest assured I will never treat your work, or anybody's work for that matter, the way you do.

**Comment by skmp** [comment]
I never saw any respect, or PRs, or chatting for plans, or feedback taken from me @flyinghead. How was that considering of me and my code from your part?

**Comment by skmp** [comment]
@flyinghead as I have said before, I don't mind marking your code as GPL, - as it is already marked for external files-, if you feel that is more fair. But when you just ghost other people, there's no way to communicate.

**Comment by ghost** [comment]
why be ashamed i dont see any issue with a bsd license still open source anyone can use it its far less restrictive...

**Comment by skmp** [comment]
I don't exactly understand myself either @grant2258. No one has explained to me their problem tbh.

**Comment by mrneo240** [comment]
> why be ashamed i dont see any issue with a bsd license still open source anyone can use it its far less restrictive...

makes it harder to make money from patreon on other's work when contributing nothing

**Comment by darcagn** [comment]
BSD license is great. Imagine being upset because someone made their software licensing less restrictive. Seems like there would be an ulterior motive for being upset in that situation....

**Comment by skmp** [comment]
Flyinghead is by far the biggest contributor -- apart from the original team. I do think he deserves to have a say, though in my view not in majority for the project. That's why this is so perplexing to me, I don't even understand what their view is.

**Comment by ghost** [comment]
> makes it harder to make money from patreon on other's work when contributing nothing

Well thats not a source code issue its a stealing money for other peoples work issue if your wanting copyleft. As far as usage goes its far less restrictive

**Comment by Holzhaus** [comment]
I would have preferred LGPL, but BSD is okay too ;-) If it was a proprietary license I could understand the reaction, but it's still open source...

**Comment by skmp** [comment]
@Holzhaus LGPL has issues on apple though, due to how it links, doesn't it?

**Comment by skmp** [comment]
Also proposed is 4-clause bsd, which asks closed uses to acknowledge they use reicast, which I think LGPL doesn't

**Comment by skmp** [comment]
Also @dmiller423 @MrPsyMan I hope it's all chill with you?

**Comment by d235j** [comment]
> Also proposed is 4-clause bsd, which asks closed uses to acknowledge they use reicast, which I think LGPL doesn't

This is inaccurate, 2- and 3-clause bsd require closed uses to acknowledge use in the documentation. [L]GPL do require all uses to acknowledge use as well in the copyright notice / documentation.

4-clause BSD requires acknowledgement *in all advertising*, which is extremely broad and would make the software GPL-incompatible.

**Comment by skmp** [comment]
Notify list: @davidgfnet @gigaherz @ptitSeb @pold500 @hooby3dfx @spielvan @reicast/members @reicast/collaborators

**Comment by Ravenslofty** [comment]
I don't have any source in Reicast, so my opinion is irrelevant :P

**Comment by skmp** [comment]
@d235j maybe 3-clause is a better choice then. I guess I'll wait for others to pitch in as well?

**Comment by skmp** [comment]
@Holzhaus we could also dual license, bsd/lgpl, as silly as it is

**Comment by ghost** [comment]
I would go with the bsd/4 for ethical reasons getting a little credit for work done is a good thing in my opinion. Again it might not be practical for other hope you all come to a choice. A lot of people wont like reading this but ill link it anyway. https://dev.to/degoodmanwilson/open-source-is-broken-g60

**Comment by davidgfnet** [comment]
Oh there we go again...
obligatory meme

**Comment by d235j** [comment]
@grant2258 BSD+4 is basically incompatible with every other license. The advertising clause is extremely broad and makes all forms of redistribution anything that contains even small portions of code very messy.

Yes, open source is broken, but going to a license incompatible with everything else will not help. We had this issue with the old MAME license.

**Maybe it would be best for @skmp to first define the WHY a relicense is desired at this time? That would make this discussion easier.**

I was heavily involved with the MAME relicense, which was quite a lot of work as we did not have a CLA and therefore had to contact past contributors. Our reasons WHY: consistency with other emulators and software in general for easier reuse of code; DFSG/Fedora guideline compatibility; moving to something more standard — over the years we've had people look at MAME, notice the license, and then decide that it was not worth contributing.

Due to the modular architecture, we have a 3BSD core, and a handful of LGPL/GPL drivers. While we don't have the build system infrastructure for it at this time, it would be possible to build a pure 3BSD binary of MAME, with some devices missing. Overall there was no pushback — though there were several people who couldn't be contacted and therefore we had to rewrite their code.

We were not particularly concerned about fields of use and the license won't prevent knockoffs — the best one can do there (short of closing source) is enforcing the trademarked name, and that's nontrivial.

**Comment by skmp** [comment]
Summarizing #455, I want reicast to be able to be used as widely as possible. I'd like us to take some credit for it, thus the /4 idea. 

I wasn't aware of the incompatibilities.

Would bsd/4  AND lgpl dual license resolve your concerns?

**Comment by ghost** [comment]
@d235j I have seen the old mame licenses being used and abused completely agree with you there. I guess the reality is open source doesnt care about the devs just the code is the reality. 

I myself wasnt aware of the 4/clause compatability with all other licenses. It a shameful state of affairs for open source not to allow the people that produced something to be credited to be honest bit that aside because it is what it is. 

I personally think a license without a copyleft clause would safe guard a project if it has a hostile takeover from a bigger organization demanding free updates on the original devs backs while treating them badly you can retain your source updates yourself and contain your project internally from any point you choose too or you are free to share as you feel gives you a certain freedom that copyleft license dosent. I guess a bsd/3 could help in that situation so you can still keep you project going and not be harassed by other making money off your work indefinitely. The good think is this doesnt happen all the time just when the entrepreneurs with a monthly patreon enter the picture they will want copyleft licenses guaranteed its there bread and butter.

**Comment by d235j** [comment]
> I myself wasnt aware of the 4/clause compatability with all other licenses. It a shameful state of affairs for open source not to allow the people that produced something to be credited to be honest bit that aside because it is what it is.
>

This isn't the case because nearly all licenses, short of public domain (and variants such as CC0 / Unlicense / WTFPL) require the people that produced the software to be credited, as part of the copyright notice included with the documentation and the about info of the software.

What 4 clause BSD does is require this credit to be included **in every single piece of advertising and marketing of the software** — e.g. telling someone to use it. It also leads to a proliferation of credits. https://www.gnu.org/licenses/bsd.html goes into this.

**Comment by ghost** [comment]
so the only real choices are New BSD License/Modified BSD License (3-clause), and the Simplified BSD License/FreeBSD License (2-clause) any maybe apache2.0 for gpl for no copyleft?

**Comment by d235j** [comment]
The main licenses that are out there / compatible are...

AGPL — strong copyleft, applies to network use, compatible with AGPL, GPL, LGPL, MPLv2, BSD, MIT, Apache, but the combination becomes AGPL. One of the most "restrictive" licenses that is still Free and Open Source Software and approved under the DFSG/Fedora guidelines.
GPL — strong copyleft, down-compatible with GPL, LGPL, MPLv2, BSD, MIT, Apache, but the combination becomes GPL.
LGPL — copyleft for the package, but allowed to be linked, as a package, to other-licensed or proprietary code. (Don't mix up linking and combining!)
MPL (v2 only) — file level copyleft, compatible with GPL/LGPL/etc.
Apache 2.0 — permissive (no copyleft), compatible with v3 versions of GPL/LGPL. Incompatible with GPLv2/LGPLv2 due to some of the patent terms, which is why LLVM has an exception.
BSD2/BSD3/MIT — permissive, basically the same set of allowances/restrictions, all require credit to be given, patents are generally not considered

Public Domain/CC0/Unlicense/WTFPL — disclaiming all copyright, no credit given — these are all variants of public domain.

The AGPL/GPLv3/LGPLv3/MPL/Apache 2.0 have strong patent terms; the others mostly don't. All that aren't public domain require credit to be given. Patents may or may not be a consideration for you.

There are various references of licenses; the ones above are ones that I consider sufficiently popular and cover a sufficiently wide range of use cases for free and open source software, while minimizing proliferation of custom/incompatible licenses.

Also see https://choosealicense.com/licenses/ , which is a website run by GitHub that has basically the same information.

**Comment by ghost** [comment]
Thanks for helping me through this maze that is really helpful the The Unlicense looks interesting

**Comment by skmp** [comment]
I say we go with BSD3.

**Comment by skmp** [comment]
Merging now as there seems to be consensus. We can re-visit again later if anyone strongly disagrees.

**Comment by baka0815** [comment]
Fine with me.

**Pull request merged**
