### PR TITLE
Fix reicast fails to render some KallistiOS scenes

### PR DESCRIPTION
**Pull request by DevilFrost**

### CODE REVIEW

**Comment by skmp** [comment]
@DevilFrost what is the rationale behind this? Why the change applies only on the FRONT face culling? As this affects behavior that most games use, have you tested it?

**Comment by DevilFrost** [comment]
@skmp this is a fix for Issue [#1229](https://github.com/reicast/reicast-emulator/issues/1229)

**Comment by flyinghead** [comment]
https://github.com/reicast/reicast-emulator/commit/6ffe4c0280ef483527cf804f44f8960ecfef7aa0#diff-566724dab6ce076b0b11d297ea1167b6 might be a better fix

**Comment by DevilFrost** [comment]
@skmp need to test games.

**Comment by dmiller423** [comment]
@DevilFrost You would need to do some testing,  not skmp if that's what you meant.  As well as some explanation as to why this is only done for translucent polys w. autosort on...  Perhaps the games flyinghead said just the xor already fixes are a good start:  "Fixes South Park Rally and Wacky Races invisible menus."

**Comment by flyinghead** [comment]
The commit I'm mentioning fixes a problem that affects all Sprites: their face orientation is reversed. This can be seen by checking the order of vertices in the resulting poly. Rather than putting the vertices in the right order, I just reversed the cull mode with the same result.

**Comment by DevilFrost** [comment]
@dmiller423 Prog.cdi draws a translucent polys autosort on and GL_FRONT. With GL_FRONT incorrect. Replacing an GL_FRONT with an GL_BACK solves the problem. I tested the Wacky Races. Menu in the Wacky Races is drawn correctly. With the fix of flyinghead, everything is also drawn correctly.

I think fix flyinghead is better.

**Comment by Protofall** [comment]
I've run some KOS tests with @DevilFrost 's fork and most of the time I'm finding master is more accurate. I made a more detailed analysis in the comments of Issue #1229 (Posted there because it gives better insight as to why master can't render Prog.cdi)

**Comment by dmiller423** [comment]
I'm not surprised,  the xor FH uses for sprites only is a bit of a hack but is more plausible without knowing what else might use similar behaviour...   It's been a long time since I've looked at this area, and I was quite busy in those days trying to fix Z-issues and implement mod volumes and such.   This is why I said it has to be tested fully,  thanks for the input @Protofall

**Pull request closed without merging**
