### PR TITLE
evdev: Allow two controls with the same event

### LINKED ISSUE #1042: Reicast crashes when two evdev_device_id_X entries match in emu.cfg
I'm attempting to get two players configured off of one input device (XArcade Tank Stick Dual if it matters), so my thought was to have two separate mappings of the device, one for each player's side, and then point them both to the same device id:

evdev_device_id_1 = 2
evdev_device_id_2 = 2
evdev_device_id_3 = -1
evdev_device_id_4 = -1
evdev_mapping_1 = /opt/retropie/configs/dreamcast/mappings/controller_XGaming XArcade.cfg
evdev_mapping_2 = /opt/retropie/configs/dreamcast/mappings/controller_XGamingXArcadeP2.cfg

np _(or nb, can't remember)_ = 2

This causes Reicast to immediately crash when opening anything. If I change one of the evdev id's, then it starts up, but the other mapping isn't used, and I can't control player 2.

Is this a bug, or am I missing something more obvious here?

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/47971205-reicast-crashes-when-two-evdev_device_id_x-entries-match-in-emu-cfg?utm_campaign=plugin&utm_content=tracker%2F500311&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500311&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by baka0815**
Includes the changes from #1239 but without the changes to ``EvdevControllerMapping`` to help test if this also works for more people than myself.

Fixes #1042 and #1035

### CODE REVIEW

**Comment by baka0815** [comment]
@TestSubject06 @SteelBattalion 
I uploaded the Linux ELF-fileof this branch  to https://www.file-upload.net/download-13267758/reicast.zip.html. Please test!

**Comment by AbandonedCart** [comment]
Is there already verification that the same key is not being assigned to two different devices? If not, that may be a good followup. That was an implied benefit of not allowing the same device to be assigned to two controllers.

**Comment by baka0815** [comment]
Yes, I checked that with SNK vs CAPCOM.
I used a different config for each player and it was working fine on my end (one button was a punch for p1 the other for p2). I didn't try assigning the same button twice.

**Comment by AbandonedCart** [comment]
The question was if it checked that you were assigning the same button twice.

**Comment by baka0815** [comment]
Just checked. Assigning the same key to both players works and both players react.
However I'm not entirely sure we want to forbid that. Maybe just inform with a console output?

**Comment by AbandonedCart** [comment]
That would also be a form of verification. Not everyone will assign every controller all at once. Some may not even realize they assigned the same key twice. Leaving everything to "ideally it works" or "as long as you follow the instructions" should be reserved for when it's absolutely necessary.

**Comment by AbandonedCart** [comment]
I'm not sure I follow. How does that justify not informing the user of an overlapping key assignment?

**Comment by baka0815** [comment]
Ah ok. I'm all for informing the user.
I just thought that you wanted to exit if a button was assigned more than once.

**Comment by AbandonedCart** [comment]
That seems excessive to me, which is why I was only asking if it checked for that.

**Comment by blackman91** [comment]
The latest dev with this merge crashes reicast when you select any gamepad abd press tge option manual mapping, here is a log:

Reconstruct Branch               : NOTHING
08-10 21:05:27.827 26695 26711 I OpenGLRenderer: Initialized EGL, version 1.4
08-10 21:05:27.828 26695 26711 D OpenGLRenderer: Swap behavior 1
08-10 21:05:28.380 26695 26700 I art     : Do partial code cache collection, code=22KB, data=31KB
08-10 21:05:28.381 26695 26700 I art     : After code cache collection, code=14KB, data=25KB
08-10 21:05:28.381 26695 26700 I art     : Increasing code cache capacity to 128KB
08-10 21:05:29.663 26695 26695 E MogaHack: Somebody is trying to intercept our intent. Disabling MOGA controller for security.
08-10 21:05:32.826 26695 26695 D AndroidRuntime: Shutting down VM
08-10 21:05:32.827 26695 26695 W System.err: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
08-10 21:05:32.827 26695 26695 W System.err: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:760)
08-10 21:05:32.827 26695 26695 W System.err: 	at com.reicast.emulator.config.InputModFragment.getButtonImage(InputModFragment.java:407)
08-10 21:05:32.827 26695 26695 W System.err: 	at com.reicast.emulator.config.InputModFragment.onViewCreated(InputModFragment.java:145)
08-10 21:05:32.827 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1355)
08-10 21:05:32.827 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
08-10 21:05:32.827 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
08-10 21:05:32.827 26695 26695 W System.err: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
08-10 21:05:32.827 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
08-10 21:05:32.827 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
08-10 21:05:32.828 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
08-10 21:05:32.828 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
08-10 21:05:32.828 26695 26695 W System.err: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
08-10 21:05:32.828 26695 26695 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
08-10 21:05:32.828 26695 26695 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-10 21:05:32.828 26695 26695 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-10 21:05:32.828 26695 26695 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
08-10 21:05:32.828 26695 26695 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-10 21:05:32.828 26695 26695 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
08-10 21:05:32.828 26695 26695 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
08-10 21:05:32.828 26695 26695 I Process : Sending signal. PID: 26695 SIG: 9
08-10 21:05:35.183 26737 26737 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-10 21:05:35.410 26737 26754 I Adreno  : QUALCOMM build                   : bc479b6, I15255e4b4a
08-10 21:05:35.410 26737 26754 I Adreno  : Build Date                       : 02/22/17
08-10 21:05:35.410 26737 26754 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
08-10 21:05:35.410 26737 26754 I Adreno  : Local Branch                     : 
08-10 21:05:35.410 26737 26754 I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.

**Comment by AbandonedCart** [comment]
@blackman91 Please add to / open issues rather than posting feedback on closed merges. It makes it very hard to track the status.

**Comment by blackman91** [comment]
Just figured it out, for some reason the buttons.png inside my themes folder makes reicast crash when I press manual on input for some reason, just renamed the image and that fixed it. It should be easy to reproduce.

**Comment by SteelBattalion** [comment]
I'm still getting a crash for can't assign device id to two ports using your uploaded elf.

**Comment by SteelBattalion** [comment]
It launches and doesn't crash. I'm able to use the same device for both player one and two. However the following strange behavior occurs. Pressing P2 Left activates P1 Y, Pressing P2 Down activates P1 LT, Pressing P2 Y activates P1 X, Pressing P2 RT activates P1 A. 

[P2USBLinx.txt](https://github.com/reicast/reicast-emulator/files/2280116/P2USBLinx.txt)
[P1USBLinx.txt](https://github.com/reicast/reicast-emulator/files/2280117/P1USBLinx.txt)

**Comment by baka0815** [comment]
Could you provide the console output?

**Comment by SteelBattalion** [comment]
[consoleoutput.txt](https://github.com/reicast/reicast-emulator/files/2280129/consoleoutput.txt)
Hopefully this is what you need.

**Comment by AbandonedCart** [comment]
Assuming that all of the keycodes are right from controller -> mapping, it looks like an issue with the key values for the Dreamcast side. I vaguely remember getting a similar report on Android.

**Comment by baka0815** [comment]
Sorry for beeing inaccurate, I meant the console output of the start of reicast. We're not logging anything while pressing keys.

**Comment by SteelBattalion** [comment]
[consoleoutput.txt](https://github.com/reicast/reicast-emulator/files/2280207/consoleoutput.txt)
Here is the start up portion of it.

**Comment by SteelBattalion** [comment]
[consoleoutput.txt](https://github.com/reicast/reicast-emulator/files/2280233/consoleoutput.txt)
As per request.

**Comment by baka0815** [comment]
Hmm, that also looks normal.

**Comment by baka0815** [comment]
@SteelBattalion I think that the X11 keyboard is also active (see #1283) and interferes.

Set ``enable_x11_keyboard`` in your ``emu.cfg`` to ``0`` and test again.

**Comment by SteelBattalion** [comment]
I had already disabled it by setting it to -1.

**Comment by baka0815** [comment]
``-1`` doesn't work (yet, see #1283), you have to set it to ``0``.

**Comment by SteelBattalion** [comment]
My apologies I misread that. I've set it to 0 and the behavior is gone. This is amazing!

**Comment by baka0815** [comment]
That's good. Since your controller is recognized as a keyboard the X11 mapping is also used. Disabling it only uses the evdev mapping.

**Pull request merged**
