### PR TITLE
Replace libpng with stb_image*

### PR DESCRIPTION
**Pull request by davidgfnet**
Dumps textures as PNG as usual (relies on zlib!) and allows loading
textures in jpg/bmp/gif and also png.

### CODE REVIEW

**Comment by skmp** [comment]
This pull request **introduces 16 alerts** and **fixes 3** when merging 8352fa44915e2e0ef632f780eac787ac85a9259a into a6b773a23e4167f953108e90711d5eeceed37f11 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-d40ac5eb56c18cde40612ee52dd382dc64ed18cd)

**new alerts:**

* 11 for Multiplication result converted to larger type
* 3 for Mismatching new/free or malloc/delete
* 1 for Unsigned comparison to zero
* 1 for Missing header guard

**fixed alerts:**

* 2 for Comparison result is always the same
* 1 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
This pull request **introduces 16 alerts** and **fixes 3** when merging 448f852879089d0c7015ee6137a4f998cde5fc4f into f6b49f20acc321556c37c7fbad954f898c1929bf - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-f5287b26fb7dd7ced8f0b42e6f84215c11f02051)

**new alerts:**

* 11 for Multiplication result converted to larger type
* 3 for Mismatching new/free or malloc/delete
* 1 for Unsigned comparison to zero
* 1 for Missing header guard

**fixed alerts:**

* 2 for Comparison result is always the same
* 1 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
@davidgfnet are there any blockers in merging this? What are the benefits?

**Comment by gigaherz** [comment]
I believe the main advantage is support for jpeg images on top of png, which would allow large texture packs to use lossy compression for opaque textures.

**Comment by davidgfnet** [comment]
There's a lot of warnings due to the way we integrated libpng (lots of define PACKAGE_VERSION and alike) that cause noise during build. Also libpng is quite a pain to integrate (see how rows need to be created and passed to the library). Using this provides a better and cleaner interface, everything goes into a single file, making it easy to upgrade in the future (I'm not a fan of building-in deps in reicast, but if we wanna go that way stb_* libs are great for that).
And yeah as giga mentions this adds jpeg and other formats.
Do we wanna add DDS support? I see some people use it for some texture packs. No idea why (since it's lossless and probably worse quality/efficiency than JPG) but we might as well support it if it comes for "free".
I need to do some more checks before we can merge this. So far it worked for me and some other users :)

**Comment by skmp** [comment]
DDS Supports DXT* compression, which the hardware also supports, so it's often used for that reason. Merging in then.

**Comment by GranvilleR** [comment]
I believe one benefit to DDS in Dolphin at least is mipmapped texture support. I'm not sure if this is relevant to how Reicast handles mipmapping though.

**Pull request merged**
