### PR TITLE
Remove unnecessary includes

### PR DESCRIPTION
**Pull request by Holzhaus**
Are these needed? I was able to compile without them.

### CODE REVIEW

**Comment by Holzhaus** [comment]
@skmp Are these still needed or can I merge?

**Comment by skmp** [comment]
Possibly not. They were included for sort() most likely, but then refactor+++. Is there any #ifdef madness going on on the related files?

**Comment by skmp** [comment]
Ahh, now this is a good example where my "don't change unless an issue" ethic comes from. In C++11 `std::swap` was moved from `algorythm` to `utility`. We still support C++98 compilers (and I'd love to avoid depending on C++11 on the core for the foreseeable future, at least when it's easy. It makes portability harder). `swap` is used in `descrambl.cpp`

**Comment by Holzhaus** [comment]
I'll close this then.

**Pull request closed without merging**
