### PR TITLE
Android: Configure peripherals independently

### PR DESCRIPTION
**Pull request by AbandonedCart**

### CODE REVIEW

**Comment by baka0815** [comment]
What's the purpose of this? Adding peripherals without (additional) controllers?

**Comment by AbandonedCart** [comment]
or to configure peripherals independently, whichever wording you like better.

https://github.com/reicast/reicast-emulator/issues/1208#issuecomment-415161153

**Comment by baka0815** [comment]
Because it shall be possible to enable 2 VMUs and a microphone with just 1 controller?

**Comment by baka0815** [comment]
Well it's not actual Dreamcast behavior but it's fine for Android I think.

**Comment by AbandonedCart** [comment]
@baka0815 reicast has forced using controller 2, port 1 as the microphone for 3 years. I expanded that so that you could now pick any of three controllers to have it plugged into. If you prefer, I can restore the original configuration and go back to locking out that port.

**Comment by AbandonedCart** [comment]
Not a whole lot of options here. 

This commit fixes Seamen, but requires the user pick a port in controller 2 - 4 for the mic. 
Reverting to the old method fixes it at the cost of hardcoding a port to act as the mic.
Adding controller 1 as an option requires unlocking it to the risk of data loss, misconfiguration, user error, and a list of other possible issues.
Doing nothing makes Seamen unavailable without a hardware controller in port 2.

Take your pick. What gets screwed?

**Comment by AbandonedCart** [comment]
Well now it will force controller 1, port 2 and *then* allow the use of any additional microphones (although I have no idea why you would have more than 1, but people deserve options)

**Comment by blackman91** [comment]
Does that mean we can no longer access vmu_save_A2.bin and that the microphone will always be enabled? Also does that mean the enable microphone(s) option in settings option is obsolete now? Should it be removed?

**Comment by AbandonedCart** [comment]
No and no.

**Comment by AbandonedCart** [comment]
The mic toggle is as it was before multiple controllers, but now enables any additional user-configured microphones along the ay.

**Pull request merged**
