### PR TITLE
evdev: If there was an error initializing a controller, don't proceed

### LINKED ISSUE #1380: [BUG?] Linux Crashes with Trace Trap and SIGSEGV
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Linux | origin/master | eacbae5b | No |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Linux latest build (from git) still crashes.

**_Debugging Steps Tested_**

**_Logs Gathered_**

```
Config dir is: /home/io/.config/reicast/
Data dir is:   /home/io/.local/share/reicast/
Personality: 00000000
Updated personality: 00000000
Linux paging: 4096 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 382D0000, aram: 582d0000, vram: 3C2D0000, ram: 442D0000
Resetting mem
Mem alloc successful!
libwebsockets test server - (C) Copyright 2010-2013 Andy Green <andy@warmcat.com> - licensed under LGPL2.1
Initial logging level 7
Library version: 1.3 c11b847
IPV6 not compiled in
libev support not compiled in
 static allocation: 4488 + (16 x 1024 fds) = 20872 bytes
Malformed entry on config - ignoring @ 44(ElfFile)
Malformed entry on config - ignoring @ 47(ta.HashCheckFile)
Malformed entry on config - ignoring @ 48(ta.HashLogFile)
 canonical_hostname = antidote
 per-conn mem: 184 + 1554 headers + protocol rx buf
 Listening on port 5678
Found 10 matching FB configs.
Chosen visual ID = 0x24
Loaded /home/io/.local/share/reicast/data/dc_boot.bin as bootrom

Loaded /home/io/.local/share/reicast/data/dc_nvmem.bin as nvram

gdrom: Failed to open image "null"
Using Recompiler
Auto-selected audio backend "alsa" (Advanced Linux Sound Architecture).
Initializing audio backend "alsa" (Advanced Linux Sound Architecture)...
recSh4 Init
Freeing fpcb

	 CodeCache addr: 0x5567a8bed000 | from: 0x5567a8bed000 | addr here: 0x5567a8beb160
evdev: Trying to open device at '/dev/input/event0'
evdev: open: Permission denied
SIGSEGV @ 2838539480 (fault_handler+0x7552296) ... 0x94 -> was not in vram
Fatal error : segfault
 in fault_handler -> /home/io/build/reicast-git/src/reicast/shell/linux/../../core/linux/common.cpp : 100 
```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [X] Place an X in the box to confirm you have filled in this form

### PR DESCRIPTION
**Pull request by baka0815**
If the controller was not correctly initialized, the fd and/or the mapping might not be set, which could then result in access violations or other errors.

This fixes #1380.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
You're probably going to need https://github.com/reicast/reicast-emulator/pull/1377
Resolves `Android NDK: APP_STL stlport_static is no longer supported`

**Comment by baka0815** [comment]
Hmm, I don't want to merge that into my pr and the failure seems unrelated to my changes.

**Comment by AbandonedCart** [comment]
Why would you merge it into your PR? It's part of a PR already.

Click the details button on your two travis failures. That is the error.

**Comment by AbandonedCart** [comment]
A simple rebase should resolve the errors.

**Comment by baka0815** [comment]
Ah, didn't see you already merged the pr. Will rebase this weekend.

**Comment by AbandonedCart** [comment]
Had to speed it along because Travis randomly decided to break everything.

**Comment by baka0815** [comment]
Git is killing me... See #1395

**Pull request closed without merging**
