### PR TITLE
Added support for pull-style audiostream, including resampling pulls.

### PR DESCRIPTION
**Pull request by gigaherz**
Only dsound and sdl2 implemented as pull style, and the dsound implementation is rather messy.

### CODE REVIEW

**Comment by skmp** [comment]
This pull request **introduces 1 alert** when merging cb26fa16fbf6c9b227c4d1c46d1b3f38ccf2e48b into ec9706876ce6bcc854bee5d4d3964af241d4f6a3 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-c4e1044a2d0529d56b0d235ea5d60ba447dc630e)

**new alerts:**

* 1 for Missing return statement

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
@gigaherz So after this we can do both pull and push audio streaming?

**Comment by gigaherz** [comment]
Yup! So far as I can tell it works, I only wanted to check the existing audio APIs to see if they needed pull-ifying, before setting this to ready, and test it in more than msvc on windows.

**Comment by skmp** [comment]
👌

**Comment by mpcore-hub** [comment]
with this fix i have a problem to build
/home/pi/RetroPie-Setup/tmp/build/reicast/shell/linux/../../core/oslib/audiostream.cpp:71:29: error: could not convert ‘0’ from ‘int’ to ‘SoundFrame’
  SoundFrame Status[4] = { 0 };

**Comment by gigaherz** [comment]
Hi @mpcore-hub, does it work if you edit that line to `{ { 0 } }`? (as in, add another layer of curly braces to it)
I don't currently have my rpi setup in a way that it is capable of compiling, but I can get it set up later if needed. However if adding the extra curly braces fixes the compilation, that would save me the trouble.

**Comment by mpcore-hub** [comment]
thx gigaherz i have change it and now works the build good job!

**Comment by gigaherz** [comment]
NP! I'll also apply the change to master to avoid future troubles with it.

**Pull request merged**
