### PR TITLE
Fix/ios and osx

### PR DESCRIPTION
**Pull request by skmp**

### CODE REVIEW

**Comment by LoungeKatt** [comment]
screen shot 2015-08-18 at 9 20 58 am

**Comment by skmp** [comment]
What platform?

**Comment by skmp** [comment]
(I tested it both on ios and osx and it works here)

**Comment by LoungeKatt** [comment]
iOS. Are you running on an actual device?

**Comment by skmp** [comment]
Yup, on my ipad. Can you try a clean compile?

**Comment by skmp** [comment]
Keep it might it might not run under xcode but only when launched on it's own. xcode can't cope with some of the speed optimizations we do yet.

**Comment by LoungeKatt** [comment]
Same thing. It's on an iPhone, though. Are you installing it as a system app?

**Comment by skmp** [comment]
I just install it via xcode

On Tue, Aug 18, 2015 at 3:29 PM, TwistedUmbrella <notifications@github.com>
wrote:

> Same thing. It's on an iPhone, though. Are you installing it as a system
> app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/pull/766#issuecomment-132205342>
> .
>



-- 
~skmp

**Comment by LoungeKatt** [comment]
Weird. Crashes either way. I'll have to charge up my iPad and try that.

**Comment by skmp** [comment]
Get on irc dammit :P

**Comment by LoungeKatt** [comment]
I meant to ask you about this. The difference between the iPad and iPhone was that the phone runs 64-bit unless the app doesn't support it. This should fix it.

(Stupid app made it comment on the commit instead of the pull. MESSY!)

**Comment by LoungeKatt** [comment]
@skmp After doing a lot of random checks, it seems if I define the value of CodeCache (and later ICache) in the memset function, it fixes the issue and the games boot fine.

**Comment by skmp** [comment]
What do you mean?

On Wed, Aug 19, 2015 at 9:24 PM, TwistedUmbrella <notifications@github.com>
wrote:

> @skmp <https://github.com/skmp> After doing a lot of random checks, it
> seems if I define the value of CodeCache (and later ICache) in the memset
> function, it fixes the issue and the games boot fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/pull/766#issuecomment-132750647>
> .
>



-- 
~skmp

**Comment by LoungeKatt** [comment]
Works: ```memset((u8*)mmap(ICache, ICacheSize, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_FIXED | MAP_PRIVATE | MAP_ANON, 0, 0),0xFF,ICacheSize);```

Crashes: ```memset(ICache,0xFF,ICacheSize);```

**Comment by LoungeKatt** [comment]
How do I send a keycode? I have been staring at the Android and Linux versions for about an hour now and the best I can come up with is that i define kcode[], set it to a value, and it's like voodoo after that.

**Comment by skmp** [comment]
Just set it, it gets read as a global variable

**Comment by skmp** [comment]
You can see my "tap to button" code that does it

**Comment by LoungeKatt** [comment]
Son of a... I was looking in the wrong file.

**Comment by LoungeKatt** [comment]
Theoretically once the listeners are fixed, 6b56db4f6c6db76409690017ed443e98c69c1950 should work

**Pull request merged**
