### PR TITLE
Wip/softrend

### PR DESCRIPTION
**Pull request by skmp**
Hacking around w/ some ancient nullDC softrend code I had on my disk. I'm quite certain the triangle math is broken/doesn't completely make sense, however it works well enough to be used for testing and gets respectable (20-30) fps even w/ texturing on my old lappy.

Screens ~
ct-ingame-softrend
doa2-demo-softrend
sc-ingame-softrend
sotb-menu-softrend
sotb-softrend

Meanwhile, during dev it was more like
jgr-psytext-1
jgr-psytext-2

### CODE REVIEW

**Comment by LoungeKatt** [comment]
@skmp I rebased this just to make sure the last commit failing wasn't the recent merge

**Comment by skmp** [comment]
_mm_free & _mm_malloc are the issue on texcache. I either need to `#ifdef` them or do a refactor of the  texcache code. The refactor is meh work, mostly because the rest of the code is so ugly, but I guess that's the way to go... Then we can merge to mainline!

**Comment by skmp** [comment]
Decided having a single source is worth more than the cleanups, which would make me postpone the merge and lead to merge conflicts. Let's see if it builds so that we merge it!

**Comment by LoungeKatt** [comment]
Haha, nice!

**Pull request merged**
