### PR TITLE
JIT: Fault based code discard

### PR DESCRIPTION
**Pull request by skmp**
- Builds on top of selective code discard
- Uses ram write tracking to discard entire pages
  - Pages invalidated once are checked via fallback smc mode, as per config
- Still has some bugs

TODO
- [x] HasPageRam cross page boundary
- [x] Fix shenmue2
- [x] Validate with more games

### CODE REVIEW

**Comment by skmp** [comment]
This pull request **introduces 1 alert** when merging b44e6d6b86317441bdcf944ad8f28d7f2f056738 into ed99a4bd0c795ffa3b4ac230f7ce288fd8fd03a2 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-d854c9e4cc8aaee43cc6a75125182fd12cc83381)

**new alerts:**

* 1 for Wrong type of arguments to formatting function

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
@reicast/testers can you please test `7c72043` once travis is done building? It'll be up in http://builds.reicast.com/#skmp/fault-based-code-discard

**Comment by skmp** [comment]
@kostantinho can you test http://reicast-builds.s3.amazonaws.com/builds/heads/skmp/fault-based-code-discard-974653e/reicast-android-debug-974653e.apk and report back here please?

**Comment by skmp** [comment]
@gigaherz @davidgfnet can I haz a review from at least one of ya?

**Comment by ghost** [comment]
@skmp I try to test the reicast android debug 974653e apk but it crashes out when I select a game to play 😔

**Review by gigaherz — APPROVED** [review]
LGTM

**Pull request merged**
