### PR TITLE
Revert "Fix to windows OpenFile dialog #1238"

### PR DESCRIPTION
**Pull request by AbandonedCart**
Breaks Android

The conversion to std::string should be reconsidered or a proper conversion performed for the Android code. This cannot be delayed for subsequent PRs, as it renders the Android build non-functional.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Branch has been restored to https://github.com/reicast/reicast-emulator/tree/pold500/fix-openfile-dialog

**Comment by skmp** [comment]
This pull request **introduces 5 alerts** when merging 4ed65fca3d169ad647c309696eaa3d46592094a1 into a1996f0fe964cd9a1a6d52002794de05f797a0ca - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-924b779a73651317485fb5ccd52bf8983ba6282b)

**new alerts:**

* 5 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pold500** [comment]
I think we need to redesign this code, because it should not affect Android at all

**Comment by AbandonedCart** [comment]
Converting all of the paths to std::string requires converting what is retrieved from the JNI to std::string, which turns into a bigger mess than simply changing a variable declaration or two.

**Comment by pold500** [comment]
I'll take a look into that and what can be done in that direction

**Comment by AbandonedCart** [comment]
In the version I am running locally, all I did was exclude the conversion to std::string
In all honesty, it hit a point where trying to make Android work with it was just too much work.

**Pull request merged**
