### PR TITLE
linux/Makefile: Add .desktop entry

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Holzhaus** [comment]
Wohooo:
Reicast in GNOME3

**Comment by Holzhaus** [comment]
#thuglife
Right Click -> Open with Reicast

**Comment by skmp** [comment]
Lololololol :D
Am 24.08.2015 16:54 schrieb "Jan Holthuis" <notifications@github.com>:

**Comment by LoungeKatt** [comment]
Word. LOL

**Comment by randomstuff** [comment]
\o/

**Pull request merged**
