### PR TITLE
Feat/less video stuttering

### PR DESCRIPTION
**Pull request by skmp**
Trying to guess what causes #602

### CODE REVIEW

**Comment by skmp** [comment]
Build up on http://reicast-builds.s3.amazonaws.com/builds/heads/feat/less-video-stuttering-a605b91/reicast-android-debug-a605b91.apk

**Comment by tabnk** [comment]
New Version work Great !!!. Thank. 

No more frame-rate stuttering in game or cut scene. :D

**Comment by tabnk** [comment]
Btw, although no stuttering but some performance drop. I'm need enable frame skip of 1 in some game to make it playable with no cracking sound.

**Comment by tabnk** [comment]
Another issue. Sonic Adventure suppose to be a 60fps game but only run at 30fps at full speed.

**Comment by skmp** [comment]
Yeah, perfomance drop is to be expected. But at least we know what causes the issue now.

**Comment by skmp** [comment]
@tabnk can you try latest master build from http://builds.reicast.com? There should be an option named "synchronous rendering" that should make this less of an issue.

**Comment by skmp** [comment]
Closing this in favor of #744

**Comment by tabnk** [comment]
Tks. I'm tried the #3eee909 build. It's work and both audio and video are in SYNC when enabled "synchronous rendering". 

But there is an issue in performance (framerate drop by half). 

Usually my TV BOX (Mali-T764 GPU) can sustain 60fps for Dead or Alive 2 but this build with "synchronous rendering" will bring down fps to 30-40 fps.

**Comment by skmp** [comment]
Let's move the convestation at #602 !

**Pull request closed without merging**
