### PR TITLE
Android: Background service (Part 1)

### PR DESCRIPTION
**Pull request by AbandonedCart**
This is a counterpart to the future support for pausing the core.

It moves termination processes from stop to destroy and instantiates a service that will keep the application active in memory when not active on the device.

### CODE REVIEW

**Comment by blackman91** [comment]
Amazing, nice job man it works great!

**Comment by AbandonedCart** [comment]
Nothing actually changed yet.

**Comment by blackman91** [comment]
What do you mean? I can now continue playing without the app restarting when I press the home button or open another app on latest beta.

**Comment by AbandonedCart** [comment]
Interesting. The service isn't actually enabled. Could be dump luck that this combined with the "proper close" changes by @flyinghead let it run for a short time. It will still eventually get killed off by the system, though.

**Comment by blackman91** [comment]
Lucky, I was playing MvsC2 then started browsing on Firefox for Android for like 20 minutes then came back to reicast and it still resumed correctly.

**Pull request merged**
