### PR TITLE
Porting libretro features back to mainstream reicast

### PR DESCRIPTION
**Pull request by AbandonedCart**
The build is absurdly slow for what is actually processed

### CODE REVIEW

**Comment by skmp** [comment]
This pull request **introduces 1 alert** when merging 408d9df937c100da4b5baff5f25f4f3309c45178 into 91dda19c4981eb5724bca98408588ada6c3514a0 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-b245f1c096e4c45bce2a1c64c45791fecbb2a0fd)

**new alerts:**

* 1 for Function declared in block

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
This pull request **introduces 1 alert** when merging e169466bd57b3cb14a0332dd6859ef0808c662a1 into 91dda19c4981eb5724bca98408588ada6c3514a0 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-f94a280038e98b7558088c756cb865d638313c94)

**new alerts:**

* 1 for Function declared in block

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
This pull request **introduces 1 alert** when merging 874cc674db0ca2c8543eb5ea8c07139695d38d93 into 91dda19c4981eb5724bca98408588ada6c3514a0 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-5610ce1acb0b4084b65eb6c5f3ad92927540708c)

**new alerts:**

* 1 for Function declared in block

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by baka0815** [comment]
Is anything fixed by this?

**Comment by AbandonedCart** [comment]
Yes

**Comment by AbandonedCart** [comment]
But possibly no

**Comment by AbandonedCart** [comment]
By default, it should do nothing. It is being able to configure it for each game independently that makes the difference, which is detailed in the source commits.

It is (in the simplest terms possible) libretro's lut hacks as actual user settings, with minor improvements along the way.

**Comment by AbandonedCart** [comment]
The specific test games for these two would be
InterruptHack - Street Fighter Alpha 3
QueueRender - Daytona USA 2001

**Pull request merged**
