### PR TITLE
rend/soft: Import the experimental core from nulldc/drkpvr, better re…

### PR DESCRIPTION
**Pull request by skmp**
…nderer modularization

- Adapted for indexed, async rendering, shared ta decoder
- This blits via a quick-and-hacky GDI blitter for now
- SSE/MMX intrins based, so not very portable
- A rather not good "reference" implementation
- At least, it's not terribly slow though
- GetTexture moved to Renderer interface

### CODE REVIEW

**Comment by skmp** [comment]
The code is from some attempt for a quad-based renderer I co-designed with @gigaherz like, in 2007? or dunno. I don't remember the details, but the attempt was to be a simd-pixel-parallel implementation, and I got meh'd on computing the texcoords/textdata in parallel. Runs fairly fast though, even with GDI blitting.

Bios menu

Soul calibur ingame

**Comment by LoungeKatt** [comment]
Windows only or would it make sense to connect the Android option for software rendering to this instead ? Especially considering using actual Android software rendering is like taking a steamer on the emu.

**Comment by skmp** [comment]
This is clearly x86 only, windows only atm. I want to make 2 softrend versions, one aiming for 100% accuracy and one aiming for portable speed, which I'd like to include on android. But something is better than nothing.

**Comment by skmp** [comment]
Also, interestingly, x64 is almost twice as fast on rendering as x86 (on msvc release build)

**Comment by LoungeKatt** [comment]
I figured as much by the one HOST_OS that showed up on the changes. Even so, I have a conversion for the Android pvr GUI option whenever the time comes. I was poking around in there anyway.

**Pull request merged**
