### PR TITLE
Remove trailing whites-spaces ins sourcecode files

### PR DESCRIPTION
**Pull request by baka0815**
This only removes the white-spaces at the end of lines in our source files (*.c, *.cpp, *.h). I omitted the whole ``deps`` folder.

### CODE REVIEW

**Comment by flyinghead** [comment]
Whaaaat? Please, don't

**Comment by baka0815** [comment]
@flyinghead why not?

**Comment by flyinghead** [comment]
Because it makes reading git history much harder, breaks git blame, and all the reasons why we don't want whitespace commits

**Comment by skmp** [comment]
I think making a single merge that fixes the issue once and for all is OK, it is easy to skip it on blame and such. Having it creep in in unrelated commits i find very disruptive though

**Comment by skmp** [comment]
Since this touches pretty much all files, i think it makes sense to also address the formatting issues in the same PR. @baka0815 you on discord so we can discuss a bit?

**Comment by skmp** [comment]
(and make CI enforce some rules, and provide rule files for popular IDEs)

**Comment by baka0815** [comment]
@skmp I had a clang format file in #1311 but there were still some discussion points open.
I reopened the PR for the formatting configuration file to discuss that there.

**Comment by skmp** [comment]
Will complete the review after the Orthodox Easter

**Comment by skmp** [comment]
@baka0815 let's close this and address it after the refactor PR is done

**Pull request closed without merging**
