### PR TITLE
Force orientation for Android

### PR DESCRIPTION
**Pull request by b10z**
As requested here #1795. This feature can be accessed by settings->general at any time, and the changes are applied instantly (no need for restart). There are three options there (force Portrait, force Landscape and Auto). Everything works fine on my Android device. If there is any issue, please let me know.  :)

### CODE REVIEW

**Review by skmp — CHANGES_REQUESTED** [review]
Can you make "auto" / the default value 0?

We generally try to make the settings in a way that "zero" is the default configuration

**Comment by skmp** [comment]
Looks good overall

**Comment by b10z** [comment]
> Can you make "auto" / the default value 0?
> 
> We generally try to make the settings in a way that "zero" is the default configuration

Ready! :D

**Review by skmp — APPROVED** [review]
Waiting for CI and then will merge

**Comment by Tyfp** [comment]
Hi i just checked it out on ad7452a and the screen hasn't. Been auto rotated at all.

**Comment by skmp** [comment]
By default it rotates to your phone. You have to set landscape from the
options if you want to force that

**Comment by Tyfp** [comment]
I kinda did that on ad7452a but the options are olny showing rotate to 90 durgree on this lgk7 phone and nothing seems to work.

**Comment by Tyfp** [comment]
Im at the settings now and it olny says rotate screen 90 even if i did that the screen will be too huge to look at therefore the screen hasn't been adjusted to size

**Comment by Tyfp** [comment]
Tried the update one to it's still showing the same thing i need help on this please.

**Comment by b10z** [comment]
hey @Tyfp ! 
Force Orientation option is under General tab in Settings. This fix has nothing to do with the option "Rotate screen 90" which is under Video tab. If you are still facing this problem, please let me know your device and android version.

**Comment by Tyfp** [comment]
Oh ok i think i got it now thanks.

**Pull request merged**
