### PR TITLE
Fix linux-dist/main.cpp formatting

### PR DESCRIPTION
**Pull request by Holzhaus**
This are just some aesthetic changes (formatting, whitespace, etc.).

Replaces the cleanup part of #745.

### CODE REVIEW

**Comment by LoungeKatt** [comment]
I was always told compiler ifdefs should not be indented. Was there a specific reason to indent them along with everything else?

**Comment by Holzhaus** [comment]
Better readability. As far as i know, back in the pre-ANSI days, compilers expected lines containing a preprocessor directive to start with a `#` character (so you couldn't indent them, because the line would then start with a space or tab character).

In modern C, this is not true anymore. I guess people still avoided indenting `#ifdef` in case someone uses an ancient (pre-ANSI C) compiler version. Today, I don't think they exist anymore.

Anyway, since we're doing C++ instead of C, we don't need to bother with this, since it has always been like that.

> A preprocessing directive consists of a sequence of preprocessing tokens. The first token in the sequence is a# preprocessing token that is either the first character in the source file (optionally after white space containing no new-line characters) or that follows white space containing at least one new-line character. The last token in the sequence is the first new-line character that follows the first token in the sequence.
*Source: [ISO/IEC 14882:1999 (C++ standard), p. 302](http://tracker.ceph.com/attachments/download/752/cpp98.pdf)*

So IMHO there isn't really a reason not to indent them.

**Comment by LoungeKatt** [comment]
Ironically, Unity automatically removes any indentation when you type a directive. It seems like a rather tedious task to manually format something for no other reason than it can be indented. I thought there might have been a benefit you knew that I was missing.

**Comment by skmp** [comment]
At last got some time to look on the changes! After a bit on thinking on it, I'd rather we stick to tab-based formating (I use 1 tab = 4 spaces). It's the visual studio default and it's what I'm most used to work with. Is there some strong reason to go with space-formating for the linux side?

**Comment by Holzhaus** [comment]
> Is there some strong reason to go with space-formating for the linux side?

Nope. I didn't even notice you we're using tabs, sorry :D

I personally prefer space, especially when you want to do something like:

```
if (foooo(somethingreallyreallyreallyreallyreallyreallylong1,
              somethingreallyreallyreallyreallyreallyreallylong2)
```

(you can't really align that with just tabs).

But that's not that important, so I can change it back to tabs (preferably after we merged #752, because I really don't want to end up in rebase hell).

**Comment by skmp** [comment]
Yup, sounds like plan. I'll reboot and then test the changes and merge if all is good!

**Pull request merged**
