### PR TITLE
[c++11] core: adding high resolution clock

### PR DESCRIPTION
**Pull request by zradoslav**
Changing _os_GetSeconds_ code to platform agnostic, enabling high resolution clock.
Also removed redundant includes.

### CODE REVIEW

**Comment by LoungeKatt** [comment]
It seems chrono is not supported by the Android NDK

**Comment by skmp** [comment]
I would not trust many environents having a good clock implementation. Maybe behind an #ifdef for unix and we wait for it to mature?

**Comment by zradoslav** [comment]
@skmp 
So you recommend just to rewrite UNIX (not ANDROID) part in such way, leaving Windows unchanged?

**Comment by skmp** [comment]
I would make a global define - USE_CPP_TIME - and use #ifs to toggle the code. Or even HOST_TIME and TIME_CPP / TIME_NATIVE (same pattern as the other config options)

**Comment by skmp** [comment]
(Cleaning up old tickets)

**Pull request closed without merging**
