### PR TITLE
Fix to windows OpenFile dialog #1238

### PR DESCRIPTION
**Pull request by AbandonedCart**
Rebased, fixed for code changes, etc. Perhaps we can get this wrapped up?

### CODE REVIEW

**Comment by AbandonedCart** [comment]
wercker: *install-dependencies failed* -> probably just requires a restart

**Comment by skmp** [comment]
This pull request **fixes 5 alerts** when merging 88c104580c5ca281209c405946a6d944a7252a51 into 7bd871490c76e52620837f4fbef050dc218f4d88 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-9a0c36affa745c32d5e99db8d3dbf66cb0f8b697)

**fixed alerts:**

* 5 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AbandonedCart** [comment]
This is getting merged once the checks complete, so any objections should be logged ASAP.

**Comment by skmp** [comment]
This pull request **fixes 5 alerts** when merging 95c06b942b5e47a65a67f70c3aa9305ec8a8350c into 7e8f558c193c360e40b614b4f256e0429bd8612c - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-fe6b13fd031ff5b6c0393ec2b0c191eaa89d20cf)

**fixed alerts:**

* 5 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pold500** [comment]
@AbandonedCart what are talking about? Can you please be more specific?

**Comment by AbandonedCart** [comment]
The code samples above have the same result.

**Comment by AbandonedCart** [comment]
@pold500 I was not aware this was not tested on Android. I am assuming that because it completely prevents loading games.

**Comment by AbandonedCart** [comment]
I did find that I was able to set a default image fairly direct from a jstring and it would load fine. The regular game loading is done through a pseudo-commandline, though. This failed no matter how it was handled, in both string and character array form. Setting a default disk to load a game is a bit of an ugly hack and should probably only be used as a last resort.

**Comment by AbandonedCart** [comment]
Resumed at https://github.com/reicast/reicast-emulator/pull/1358

**Comment by pold500** [comment]
@AbandonedCart OK, I can test it on Android and make appropriate corrections, but I've no idea what "null check" you're talking about, and what is actually wrong in my code. Is that those preprocessor checks that corrupt the logic?

**Comment by AbandonedCart** [comment]
@pold500 Forget about that comment. One is before your original change, the other is after. @skmp made a line comment about leaving the #'s inside the if and I was pointing it that it didn't matter.

**Comment by AbandonedCart** [comment]
Also, in case you didn't see it on the re-opened PR, @baka0815 stated:

> After pressing cancel the emulator closes, previously the BIOS started.
> I would like to keep the previous behavior to be able to run the BIOS.

**Pull request merged**
