### PR TITLE
Re-applying patches with Android workaround

### PR DESCRIPTION
**Pull request by AbandonedCart**

### CODE REVIEW

**Comment by skmp** [comment]
This pull request **fixes 1 alert** when merging ec077f958c0bde334712b157584fd87d0171a49f into 223cd74824ab4a2dd9440eb4c9c4a0a3d1492712 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-406c7a4c987e8d9e8c9dace013ae463dd56afed6)

**fixed alerts:**

* 1 for Too few arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
This pull request **fixes 1 alert** when merging 65d44c604a1980bd16c21b464b42f724f0707936 into 223cd74824ab4a2dd9440eb4c9c4a0a3d1492712 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-9ba50715acf3ccb0ed4e0a78278f8a0146b755ea)

**fixed alerts:**

* 1 for Too few arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by skmp** [comment]
This pull request **fixes 1 alert** when merging 68ce118a0ef98884826c81119ee6cd0a5d1e2dcc into 223cd74824ab4a2dd9440eb4c9c4a0a3d1492712 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-b2684cb28ea7e6bb58736970d4e3bd9c3145cef0)

**fixed alerts:**

* 1 for Too few arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AbandonedCart** [comment]
@skmp AppVeyor is broken

> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\projects\reicast-emulator\shell\reicast.vcxproj]

**Comment by baka0815** [comment]
v141 is VS 2017, we use 2013 AFAIK?

**Comment by AbandonedCart** [comment]
https://github.com/reicast/reicast-emulator/commit/3579c9aabf673c241253ce184f394a5ec293d848

2015

**Comment by AbandonedCart** [comment]
...might as well also fix the Android formatting while I'm in there.

**Comment by skmp** [comment]
This pull request **fixes 1 alert** when merging ca510c100988e7f795deec3622eefb74ecb94b64 into 223cd74824ab4a2dd9440eb4c9c4a0a3d1492712 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-338aa182b307e17e60ecb10fd7ef6bcfe8867df0)

**fixed alerts:**

* 1 for Too few arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AbandonedCart** [comment]
@dmiller423 https://cla-assistant.io/reicast/reicast-emulator?pullRequest=1303

**Comment by skmp** [comment]
This pull request **fixes 1 alert** when merging 8f82e926b8626ece07cb0b0cc34ebcd3d0930c2d into 7ff9d0ec02ace07f63d170a6b8b0503c689d15ad - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-ecc4ea53edf6a82da25e5ee411a3698893fbd029)

**fixed alerts:**

* 1 for Too few arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
