### PR TITLE
Linux: Enable x11 fullscreen toggling and fix window resizes

### LINKED ISSUE #761: [Linux] X11 window doesn't resize properly
Currently, x11 window resizing isn't implemented yet.

I'm able to catch window resize events and query the new size of the window, but since I don't have any OpenGL experience, I don't know how to make the video output fill the new window size.

### PR DESCRIPTION
**Pull request by Holzhaus**
This one enables toggling fullscreen with the F11 key and also fixes window resizing. Resolves #761.

For avoiding merge conflicts, we need to merge #752 & #764 first.

### CODE REVIEW

**Comment by meveric** [comment]
once again.. having a button as the only method to switch to full screen mode can be troublesome..
Imagine a scenario with a device running as a console with only Joystick control but no keyboard connected.
It would be better to have a config option as well to switch to full screen mode, rather than only rely on the keyboard alone.

**Comment by Holzhaus** [comment]
Sure I'll add that when I have the time, but being able to fullscreen the app at all was a priority ;-)

**Comment by Holzhaus** [comment]
@meveric commit 4dee565 should make you happy :D

**Comment by skmp** [comment]
Looks good to me. Finally proper x11 fullscreen support :+1:

I know formatting is important, but let's try to keep the formatting changes on separate PRs. It helps when I read the diffs (and I read a ton of diffs these days -.-)

**Pull request merged**
