### PR TITLE
Add a generic 32-bit ARM rule.

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
It can be useful in places like launchpad farm.

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
@skmp are there anything wrong with this commit?

**Comment by sergiobenrocha2** [comment]
Many boards nowadays comes with neon support in the SoC

**Comment by skmp** [comment]
I think what would be best is to auto-detect the current platform,

`uname -m` works for thearchitecture (eg, arm7l) and `ls /lib/* | grep armhf` to detect armhf or not. Reicast requires at least neon-vfp16. You can do `cat /proc/cpuinfo | grep Features` which gets us a list like `half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm`. Reicast requires `vfpv3` or `vfpv4` and `neon`. `vfpd32` is optional (the JIT doesn't use the extra registers, but clang/gcc might if you enable it)

**Comment by skmp** [comment]
Launchpad does cross compiles though? Detection logic only helps for when target and build machine are the same

**Comment by sergiobenrocha2** [comment]
Launchpad uses Qemu to build ARM packages.

**Comment by skmp** [comment]
Qemu *URGH*

**Comment by skmp** [comment]
(I still haven't made up my mind if we should default to arm or not, which is why I haven't merged this in yet)

**Comment by Holzhaus** [comment]
@skmp Actually, we woudn't default to ARM in all cases - just if it's actual ARM hardware (and thus `$ARCH` contains the string `arm`: https://github.com/sergiobenrocha2/reicast-emulator/blob/master/shell/linux/Makefile#L36-L60

**Comment by skmp** [comment]
Hah, I failed to notice that part. Yeh, that makes perfect sense.

**Pull request merged**
