### PR TITLE
Update for ndk-10d, improved build options

### PR DESCRIPTION
**Pull request by skmp**
Today I found out that android by default exports all symbols, and uses dynamic linking on them. This applies even for "internal" symbols, as everything is exported by default. Some other opts were enabled too, and minor changes on nixprof/common/travix for ndk r10d.

- Makes all symbols hidden by default (pro tip: `nm -D <so file>`)
- Disables all debug info. Debug info is *not* always zero cost on gcc.
- Enable per function GC
- ndk r10d uses same register names as desktop linux (yay!)

Would be great if someone tested the speed of these changes and reported back. Use [this CI build apk](http://reicast-builds.s3.amazonaws.com/builds/heads/features/use-ndk-r10d-7abd154/reicast-android-debug-7abd154.apk).

### CODE REVIEW

**Comment by skmp** [comment]
While we're waiting for travis to build, some stats

Before
`
$ nm -D armeabi-v7a/libdc.so | grep " T " | wc -l
2343
$ ls armeabi-v7a/libdc.so
11150976
`

After
`
$ nm -D armeabi-v7a/libdc.so | grep " T " | wc -l
634
$ ls armeabi-v7a/libdc.so
10851676
`

Also for mips 2.2M -> 1.7M && x86 1.9M -> 1.5M.


`

**Comment by skmp** [comment]
*Updated desc. with test apk link*

**Comment by hooby3dfx** [comment]
I wonder if this fixes soul calibur legs issue

**Comment by hooby3dfx** [comment]
hahaha!! this resolves https://github.com/reicast/reicast-emulator/issues/83

it did freeze though after playing for ~5 mins, but that may be due to other issues.

**Comment by skmp** [comment]
I guess that's reason enough to merge it then :+1:

**Comment by skmp** [comment]
We have been getting a lot of "freeze-after-5-mins" reports, too, and that
is worrisome.  Also, function-sections and data-sections should be checked
for speed regressions... I don't quite trust gcc that much.

On Tue, Mar 31, 2015 at 4:54 AM, Bryan Barnes <notifications@github.com>
wrote:

> hahaha!! this resolves #83
> <https://github.com/reicast/reicast-emulator/issues/83>
>
> it did freeze though after playing for ~5 mins, but that may be due to
> other issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/pull/617#issuecomment-87912070>
> .
>



-- 
~skmp

**Comment by hooby3dfx** [comment]
yes... see my issue spam.

**Comment by LoungeKatt** [comment]
I am not sure if $ANDROID_HOME is set by default or if it is just stepping over that, but adding this in (and the subsequent merge) pointed out that there are still two lines that call $ANDROID_HOME to set the tools and platform-tools.

**Comment by LoungeKatt** [comment]
This should be merged. It's been working so far.

**Comment by skmp** [comment]
Yeah, I agree. I'd love to see if the new settings affect performance, but it's so hard to measure with such uncertainty in android.

**Comment by skmp** [comment]
Hum, build fails with "/usr/local/android-sdk/tools/ant/build.xml:698: null returned: 1"

**Comment by skmp** [comment]
Assuming the build passes I'm merging this

**Comment by skmp** [comment]
Okay, now we get 

[exec] Android NDK: WARNING: APP_PLATFORM android-19 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml    
     [exec] Android NDK: E/home/travis/build/reicast/reicast-emulator/android-ndk/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.RROR:/home/travis/build/reicast/reicast-emulator/android-ndk/sources/cxx-stl/stlport/Android.mk:stlport_shared: LOCAL_SRC_FILES 
     [exec] points to a missing file    
     [exec] Android NDK: Check that /home/travis/build/reicast/reicast-emulator/android-ndk/sources/cxx-stl/stlport/libs/armeabi-v7a/thumb/libstlport_shared.so exists  or that its path is correct   


I have no idea why

**Comment by skmp** [comment]
The required file seems to exist on the archive downloaded from google `android-ndk-r10d-linux-x86_64.bin\android-ndk-r10d\sources\cxx-stl\stlport\libs\armeabi-v7a\thumb\` contains `libstlport_static.a` and `libstlport_shared.so`

**Comment by skmp** [comment]
Hum, re-running the build a couple of times fixed it. So much for travis reliability

**Pull request merged**
