### PR TITLE
OSX support

### PR DESCRIPTION
**Pull request by skmp**
- OSX shim (window, setup), basic stuff working (rec-cpp, 3d, no-exc)
- xcode workspace shared between IOS & OSX
- None of the IOS & OSX source is shared atm, left for a later PR

### CODE REVIEW

**Comment by skmp** [comment]
@LoungeKatt looks like my ios toolchain is broken atm, can you verify the ios build still works?

**Comment by LoungeKatt** [comment]
Give me like 15 minutes. Just saw this.

**Comment by LoungeKatt** [comment]
So basically http://stackoverflow.com/questions/19619710/xcode-install-on-osx-10-9-clang-error-no-input-files is where we stand.

**Comment by skmp** [comment]
@LoungeKatt can you rebase this for 95b39b885a15c9aa970ccf21fd9bb288d84290f4 and merge it? Not in OSX atm, and it would be great to have it in mainline!

**Comment by LoungeKatt** [comment]
aye_sir_by_own_beauty-d60n36c

**Comment by LoungeKatt** [comment]
@skmp Let me know after you get a chance to test that. I am still getting the error about missing files, but I have a feeling it has nothing to do with the project. It's something with Xcode.

**Comment by skmp** [comment]
I'll test it next time I boot OSX, later today. Thanks :dancers:

**Comment by LoungeKatt** [comment]
I just upgraded to Yosemite. I'll see if that clears anything up, since it looks like a 10.9 issue. They made a lot of interesting changes to Xcode recently.

**Comment by LoungeKatt** [comment]
Alright, so it turns out that even though the project files are now on the top level (not in a second emulator subfolder), Xcode still needs the reicast-ios/ prefix, but can't detect it based on the relative path (which is just /). It's a really backwards layout (Apple's linking, that is).

I have everything identified, but it is still giving the
```clang: error: no such file or directory: '/Users/loungekatt/Public/Dropbox/ReicastEmulator/reicast-emulator-lk/shell/core/rec-ARM/ngen_arm.S'``` error. Hopefully I can get that resolved, since it is still there on Xcode 6.1, 6.4, and 7.0 (beta 5)

**Pull request merged**
