### PR TITLE
[DO NOT MERGE] Continuation of (I don't know the numbers)

### PR DESCRIPTION
**Pull request by AbandonedCart**

### CODE REVIEW

**Comment by AbandonedCart** [comment]
The irony of a point becoming moot as soon as you make it...

**Comment by baka0815** [comment]
Just curious: Why was this mergen where there is the "DO NOT MERGE" info in the header?

**Comment by AbandonedCart** [comment]
https://github.com/reicast/reicast-emulator/pull/1407
https://github.com/reicast/reicast-emulator/pull/1413

The trend being both of them were merged before everything was verified.

**Comment by MrPsyMan** [comment]
Yeah, jumped into conclusions fast cause it looked pretty and such.

The sooner you fix it the sooner we'll have a pretty ui to work with.

**Comment by AbandonedCart** [comment]
This was the last part. The forced update to API 26 means using all the half-implemented stuff, like enforcing tint that only works on vectors and vectors that only work in menus.

**Comment by MrPsyMan** [comment]
Yeah, google -_-

**Pull request merged**
