### PR TITLE
linux-dist: Remove unneeded code

### PR DESCRIPTION
**Pull request by Holzhaus**
Do we need the curses code? I can't see it serve any particular purpose right now. Might be a leftover from ages ago.

### CODE REVIEW

**Comment by skmp** [comment]
Yes, we do. I use it when testing over ssh to some devboard (very common for my setup)

**Comment by Holzhaus** [comment]
Hmm, it works fine for me without it (ran it via ssh). Anyway, if you need it, can't you just run `stty echo -icanon`?

**Comment by skmp** [comment]
IIRC the point of the code is for non-blocking stdin. Ill double check it when on my lappy

**Comment by Holzhaus** [comment]
Non-blocking stdin should be possible via:

```
stty echo -icanon time 0 min 0
```

**Comment by skmp** [comment]
I haven't used stty before, and it looks like it would work, but still I prefer reicast setting it up. It's reicast's responsibility to setup the input to a sate that it works for itself (and to cleanup afterwards, which atm doesn't happen because of unclean exits)

**Comment by Holzhaus** [comment]
Where does reicast read from stdin though?

**Comment by skmp** [comment]
Hum, it used to be on [man.cpp](https://github.com/reicast/reicast-emulator/blob/a90a2cf91c1f2329ae5ea182d7283a3825ce1133/core/linux-dist/main.cpp#L457). I don't know where this code resides atm though

**Comment by skmp** [comment]
Hum, looks like you got rid of the code on the evdev changes. Hrfm.

**Comment by Holzhaus** [comment]
You may slap me in the face now. I removed it in 14ea9e4196f763638ce3f206c74adb69af610c22. I'll readd `stdin` input in a separate PR, ok?

**Comment by skmp** [comment]
Nah don't worry too much about it. Apart form me I'm not sure anyone else uses that part. Since the input stuff is getting so much re-work let's get rid of this and I can re-add next time I need in a cleaner way.

**Comment by skmp** [comment]
Wthat's `sys/soundcard.h` used for though?

**Comment by skmp** [comment]
Oh that was an unrelated whitespace change. k, merging...

**Pull request merged**
