### PR TITLE
Clean up linux-dist/main.cpp and make evdev/joystick device configurable

### PR DESCRIPTION
**Pull request by Holzhaus**
Wow, this one looks bigger than it actually is. This one mainly fixes identation (that's why this changes so many lines), parameter spacing, etc. I also unraveled the evdev/joystick code a bit.

### CODE REVIEW

**Comment by Holzhaus** [comment]
- As far as I can see, [lines 405-427](https://github.com/reicast/reicast-emulator/blob/holzhaus/linux-dist-cleanup/core/linux-dist/main.cpp#L405-L427) are obsolete. Can I delete them?
- What are lines [733-773](https://github.com/reicast/reicast-emulator/blob/holzhaus/linux-dist-cleanup/core/linux-dist/main.cpp#L733-L773) for? Do we still need them?

**Comment by Holzhaus** [comment]
Wow, became quite big, mostly because of the indentation fixes and moving stuff into separate files.

This also adds Multiplayer support (yay!) and completely rewritten input code (evdev).

Please test.

**Comment by skmp** [comment]
I'll re-work/cherry-pick this to not have the white-space changes (which we can do on a separate commit -- I hate mixing them w/ actual code changes). Thanks for the great work :+1: :+1:

**Comment by Holzhaus** [comment]
The white-space change is just the first commit. I can put it into another branch :D

**Comment by Holzhaus** [comment]
I'm reordering some commit so that they make more sense. I'll push that soon.

**Comment by Holzhaus** [comment]
Closed in favour of #751 and #752.

**Pull request closed without merging**
