### PR TITLE
cmake build (currently Linux only)

### PR DESCRIPTION
**Pull request by randomstuff**
Just a proposition, in case someone is interested. Tested on x86 and x86_64 Linux with basic options.

### CODE REVIEW

**Comment by skmp** [comment]
Hrfm, after some thinking, I'm still not quite ready to give up on the makefiles. Do you think it makes sense to have both in parallel on the repo?

**Comment by randomstuff** [comment]
Yes, I guess it does:  the cmake may have some issues anyway. It adds some maintenance burden but it should not be too much.

**Comment by skmp** [comment]
Okay, can you relocate the file to shell/cmake then pls ? :)

**Comment by skmp** [comment]
Also, beware of https://github.com/reicast/reicast-emulator/issues/455

**Comment by randomstuff** [comment]
Yes, OK. Moved and rebase agaainst master.

There is a strong expectation that the `CMakeLists.txt` is a the root of the source directory, though.

**Comment by skmp** [comment]
That makes sense for cmake-based projects, but we have many build systems, and polluting the root dir doesn't look pretty to me. Looks good, I'm merging

**Comment by skmp** [comment]
Gah, on a second thought can the toolchains be also moved into the cmake folder? *pretty pls*

**Comment by randomstuff** [comment]
Yes, I forgot it. Sorry :)

**Comment by randomstuff** [comment]
Updated.

**Pull request merged**
