### PR TITLE
rpi stuff from OrN: omx audio backend, and dispmanx window

### PR DESCRIPTION
**Pull request by gizmo98**
Use hardware upscaling. Render resolution is 640x480. Render resolution will be upscaled to the current output resolution.

### CODE REVIEW

**Comment by skmp** [comment]
Looks like linux/x11 build is failing (Bool is reserved for some x11 type?). 

Rendering at 640x480 and then upscaling has totally different results than rendering at the native resolutions directly. I think it should be an option?

**Comment by gizmo98** [comment]
I will take a look. I use OrNs patch without any problem for some time now with pis. The raspberry pi has a limited gpu. Resolutions above 640x480 are not really playable. So you can lower your output resolution to 640x480 or upscale a render resolution to your actual display resolution (for example 1080p). Dispmanx upscaling looks most of the time better than any TV upscaler and should be better than gles upscaling. It is also possible to modify the scaling kernel. It would be nice to have this patch upstream.

**Comment by skmp** [comment]
I would love to merge this in. Can you verify the code is MIT-license compatible? (See #455 for more information)

**Comment by escalade** [comment]
Getting the same Bool declaration error:

`armv7ve-libreelec-linux-gnueabi-g++   -I/opt/vc/include/ -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -I../linux-deps/include -I../../core -I../../core/deps -I../../core/khronos  -D TARGET_BEAGLE -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer -D SUPPORT_DISPMANX  -marm -march=armv7-a -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hard -funroll-loops  -fno-rtti -fpermissive -fno-operator-names -D SUPPORT_DISPMANX -D USE_EVDEV -D USE_JOYSTICK -D USE_OMX -D USE_ALSA -D USE_OSS -DGLES ../../core/linux-dist/main.cpp -o obj-dreamcast-rpi2/linux-dist/main.build_obj
In file included from ../../core/khronos/EGL/eglplatform.h:99:0,
                 from ../../core/khronos/EGL/egl.h:36,
                 from ../../core/rend/gles/gles.h:12,
                 from ../../core/rend/gles/gles.cpp:2:
../linux-deps/include/X11/Xlib.h:86:14: error: two or more data types in declaration of 'parameter'
 #define Bool int
              ^
../../core/cfg/cfg.h:18:66: note: in expansion of macro 'Bool'
 void  cfgSaveBool(const wchar * Section, const wchar * Key, bool Bool);
                                                                  ^~~~
make: *** [Makefile:331: obj-dreamcast-rpi2/rend/gles/gles.build_obj] Error 1`

**Comment by gizmo98** [comment]
I get Bool declaration error with raspbian stretch and GCC 6.3. Bool seems to be a type now. Renaming `bool Bool` to `bool Enable` fixes this problem. I will update the PR.

**Comment by skmp** [comment]
@gizmo98 doy ou have time fix the Bool issue, test this over the current master and sign the CLA? Would like to cut down in open PRs

**Comment by gizmo98** [comment]
I will take a look later.

**Comment by skmp** [comment]
Alright. Let's close this PR then. Would be great if you can rebase on top of current master while you're at it

**Pull request closed without merging**
