### PR TITLE
CloudRoms: First implementation using http

### PR DESCRIPTION
**Pull request by skmp**

### CODE REVIEW

**Review by skmp — COMMENTED** [review]
Looks OK to me overall. The donwloading implementation is petty horrid, but I didn't want to add another dependency for libcurl right now.

I've tested it and it works on linux and PC, will test the android alpha

**Comment by skmp** [comment]
This pull request **introduces 1 alert** when merging 8dd1dc5c910b01fd1008713da9751c37151e4560 into 3ca92936e15e2d64ee46efef001776b68ee51112 - [view on LGTM.com](https://lgtm.com/projects/g/reicast/reicast-emulator/rev/pr-0c069bd037247471dea8207a3ed9455fac19e9e5)

**new alerts:**

* 1 for Missing header guard

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ghost** [comment]
@skmp what this is all about? sorry for asking ✌

**Comment by ghost** [comment]
Screenshot_2019-07-22-20-06-17
To slow to download 🤷

**Comment by skmp** [comment]
@Emulatorer #1697 should have improved the speed, can you test a newer build?

**Pull request merged**
