### PR TITLE
Issues: Fix formatting and remove default image

### PR DESCRIPTION
**Pull request by AbandonedCart**

### CODE REVIEW

**Comment by LoungeKatt** [comment]
No reason to have every issue include some Github icon

**Comment by baka0815** [comment]
@AbandonedCart we should port this to the gamedb project.

**Comment by AbandonedCart** [comment]
Port what? This was pulling box art from a website to act as game icons. Supposedly, images for the games can be pulled directly from the ROM. That would still beat any other website source.

**Comment by AbandonedCart** [comment]
Right. Was thinking of the recent https://github.com/reicast/reicast-emulator/commit/b56d0f09c933c76fcf4058e34e9888cec3a134a3 not the commit from over a month ago.

**Comment by AbandonedCart** [comment]
If you want to port it, by all means. If you want me to port it, then it will have to get in line behind a long list of other things already in the works.

**Pull request merged**
