### PR TITLE
Change Social Tab (columns)

### PR DESCRIPTION
**Pull request by Morphine-git**
Added Reicast Guide and fixed hyperlinks in social tab. Social tab should look better.

### CODE REVIEW

**Comment by skmp** [comment]
@morphine-git can you upload a picture of how it looks after your changes?

**Comment by Morphine-git** [comment]
@skmp Sure, I think this one is good. You could add more hyperlinks or the small guide video (include enlarge video). 

demo

I will do another PR for the other picture. That's if you like 2nd screenshot the most. 

demo2

**Comment by skmp** [comment]
My only worry is how this looks on devices with smaller screens. Also, you need to sign the CLA in order for us to merge things in the repo. Make sure you read and you understand it :)

**Comment by Morphine-git** [comment]
I signed the CLA. Do you really like first screenshot?

**Review by skmp — APPROVED** [review]
LTGM

**Pull request merged**
