### PR TITLE
sync: Also sync to video if too fast

### PR DESCRIPTION
**Pull request by skmp**
This replaces #648 in a nicer way. Needs to be tested with problematic hardware.

### CODE REVIEW

**Comment by skmp** [comment]
@LoungeKatt we also need an option for this for android ~ *pretty pls*

**Comment by LoungeKatt** [comment]
Gotcha. Should that override the Turbo stuff or do you think they'd play nice?

**Comment by skmp** [comment]
Btw, dreamcast builds were broken after the naomi merge, just fixed on master...

**Comment by skmp** [comment]
Turbo would conflict w/ this, as it caps the top speed to have more fluid visuals. In turbo mode, it should be disabled. We need to also overhaul how the settings stuff gets applied and all..

**Comment by LoungeKatt** [comment]
It was still building Android. Got lucky I guess. 

It disables turbo. You can still turn sound off, though.

**Comment by skmp** [comment]
I'm still not sure this is better than not having a fix at all, but it's a starting point for future work so I'll merge it in. ~~

**Pull request merged**
