### PR TITLE
Fix corruption of GDI track path in reicast code

### PR DESCRIPTION
**Pull request by zradoslav**
HEAD: 407fe44
OS: Arch Linux x64

I face with a crash if trying to run _reicast_ with any GDI image:
```
$ reicast Shenmue\ -\ Ichishou\ Yokosuka\ v1.007\ \(1999\)\(Sega\)\(NTSC\)\(JP\)\(Disc\ 1\ of\ 4\)\[\!\]\[HDR-0016-0267\ 1MB3,\ 1MB4,\ 1MB5\].gdi

...

GDI : 6 tracks
OSD: 6
file[1] "track01.bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:0
Error opening /home/algamest/.local/share/reicast/data/buttons.png
Verify Failed  : file!=0
 in RawTrackFile -> ../../core/imgread/common.h : 273 
```
I believed this bug was fixed in #1084, but it's still present in current _master_ builds.
When I checked _strace_ logs I found track path corruption in GDI code:
```
$ strace reicast Shenmue\ -\ Ichishou\ Yokosuka\ v1.007\ \(1999\)\(Sega\)\(NTSC\)\(JP\)\(Disc\ 1\ of\ 4\)\[\!\]\[HDR-0016-0267\ 1MB3,\ 1MB4,\ 1MB5\].gdi

...

openat(AT_FDCWD, "Shenmue - Ichishou Yokosuka v1.007 (1999)(Sega)(NTSC)(JP)(Disc 1 of 4)[!][HDR-0016-0267 1MB3, 1MB4, 1MB5].gdi", O_RDONLY) = 15
fstat(15, {st_mode=S_IFREG|0644, st_size=182, ...}) = 0
lseek(15, 0, SEEK_SET)                  = 0
fstat(15, {st_mode=S_IFREG|0644, st_size=182, ...}) = 0
lseek(15, 0, SEEK_SET)                  = 0
read(15, "6\r\n1 0 4 2352 track01.bin 0\r\n2 1"..., 182) = 182
lseek(15, 182, SEEK_SET)                = 182
close(15)                               = 0
write(1, "\nGDI : 6 tracks\n", 16
GDI : 6 tracks
)      = 16
write(1, "file[1] \"track01.bin\": FAD:0, CT"..., 59file[1] "track01.bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:0
) = 59
openat(AT_FDCWD, "Shetrack01.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
write(1, "Verify Failed  : file!=0\n in Raw"..., 80Verify Failed  : file!=0
 in RawTrackFile -> ../../core/imgread/common.h : 273 
) = 80
write(1, "\n", 1
)                       = 1
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 13354
gettid()                                = 13354
tgkill(13354, 13354, SIGTRAP)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGTRAP {si_signo=SIGTRAP, si_code=SI_TKILL, si_pid=13354, si_uid=1000} ---
+++ killed by SIGTRAP (core dumped) +++
```

I doubt for multiple string casting (C to C++ to C), so please review & comment.

### CODE REVIEW

**Comment by LoungeKatt** [comment]
Was there an issue with how it was done in https://github.com/reicast/reicast-emulator/pull/1098?

**Comment by zradoslav** [comment]
Sorry, I haven't noticed that PR. My one therefore is a clone of #1098, but with no Windows support.

**Comment by skmp** [comment]
@zradoslav I further updated #1098, can you take a look if it works for you?

**Comment by zradoslav** [comment]
@skmp Updated #1098 works in all cases for GDI images. Thanks!

**Comment by LoungeKatt** [comment]
Closed in favor of #1098. Thanks for testing @zradoslav

**Pull request closed without merging**
