### PR TITLE
Merge branch 'master' into skmp/android-studio

### PR DESCRIPTION
**Pull request by LoungeKatt**

### CODE REVIEW

**Comment by skmp** [comment]
@LoungeKatt isn't it better to rebase `lk/android-studio-core` and work from there?

**Comment by skmp** [comment]
Also @williansti, do you mind signing the CLA?

**Comment by LoungeKatt** [comment]
That would make sense if you wanted to replace your branch with that one. I wasn't sure how you wanted to go about that.

**Comment by LoungeKatt** [comment]
Closing in favor of upcoming rebase on master.

**Comment by williansti** [comment]
@skmp sorry for the delay, signed.

**Pull request closed without merging**
