### PR TITLE
Updated EmulatorView.mm

### PR DESCRIPTION
**Pull request by brand175**
adds dpad (joystick alt) controls. This won't work is the PadVeiwController.xib file isn't added to the project.

### CODE REVIEW

**Comment by skmp** [comment]
@brand175 any idea why the build is failing? Also, can you add both files in a single MR? Thanks :)

**Comment by LoungeKatt** [comment]
@skmp This is from https://github.com/reicast/reicast-emulator/issues/1145 and was replacing the joystick with a dpad simply to avoid resolving the joystick.

**Comment by brand175** [comment]
@skmp I think it would be better not to merge the PR. Since it would be better if the joystick wasn’t a d-pad. I’ll redo the Touchscreen Triggers PR though.

**Comment by skmp** [comment]
Closing in favor of #1221.

**Pull request closed without merging**
