### PR TITLE
msvc: Update sln files to use "x86" instead of "win32" for appveyor

### PR DESCRIPTION
**Pull request by skmp**
Getting everything working for appveyor, building all 4 configurations

### CODE REVIEW

**Comment by skmp** [comment]
Rebased to msater for Wercker fixes ~

**Comment by skmp** [comment]
Okay, building release for windows takes a while (~ 30 mins, because of enabled global optimizations). I'm thinking of doing debug only builds for now, and enable release building for when we upgrade to a plan w/ more beefy cpus!

**Comment by skmp** [comment]
Okay, debug builds take 1 min each :d Still queing time can be quite high, but wooohoo!!!

**Comment by Holzhaus** [comment]
Nice work :D

**Comment by harissut** [comment]
ok im waiting this windows x86/x64.thanx

**Pull request merged**
