### PR TITLE
Sonic182/azure testing

### PR DESCRIPTION
**Pull request by sonic182**
Reopen of https://github.com/reicast/reicast-emulator/pull/1741#issuecomment-595418062

### CODE REVIEW

**Comment by skmp** [comment]
@einstein2x can you take a look on the rest of the osx/ios changes here?

**Comment by einsteinx2** [comment]
Yep I used this as a starting point, then updated the Linux section to match the Travis CI config and updated the Mac section with the extra brew dependency install step that's required now since my other changes. Hopefully it works first try, I've never used Azure CI before 🤞

**Comment by einsteinx2** [comment]
Added a shout out to @sonic182 in my PR for the help! Was much easier starting from a working example :)

**Comment by sonic182** [comment]
Hi, I did run the build with the last commit I had and It worked in Linux but not for Mac (as the last time...) here you could see the build https://dev.azure.com/johander-182/reicast/_build/results?buildId=243&view=results

But yes, @einsteinx2 you could get the azure-pipelines.yml file to your pr and activate azure for your account to continue with it, or maybe we could merge this branch to yours

**Comment by sonic182** [comment]
Oh, you already did it, nice hahaha @einsteinx2  thanks for the comment

**Comment by skmp** [comment]
I'm closing this in favor of #1825 as it has been integrated there. Thanks for your hard work @sonic182. 

Do you also know how I enable the azure pipelines for the project? I tried to do it from MSFTs site but I failed somehow o.O

**Comment by sonic182** [comment]
@skmp I usually allow it by sign in azure devops portal, with my microsoft account (hotmail or outlook or Skype...)

-> https://azure.microsoft.com/en-us/services/devops/?nav=min

Somewhere you sould allow azure app access to the repo

**Pull request closed without merging**
