### PR TITLE
Updated PadViewController.xib

### PR DESCRIPTION
**Pull request by brand175**
replaces the joystick with a dpad

### CODE REVIEW

**Comment by LoungeKatt** [comment]
While this is viable as a personal workaround, reicast does have an obligation to provide the same functionality across platforms.

**Comment by skmp** [comment]
Can you explain better what this change does? Also, CI is failing

**Comment by skmp** [comment]
Is this independent from #1221? Can we have a screenshot of what this actually changes?

**Comment by brand175** [comment]
https://www.dropbox.com/s/c07fpe8ohm26tii/Photo%202018-07-18%2C%2012%2008%2020%20PM.png?dl=0

**Comment by baka0815** [comment]
I would second the comment from @loungekatt.
The anologue should stay analogue and not be replaced with a dpad.
The real DC does not have two dpads.

**Comment by skmp** [comment]
Will close this one for now, as we're waiting for the other xcode branch to also have a PR. @LoungeKatt any updates on that?

**Comment by LoungeKatt** [comment]
It's a trainwreck...

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/pull/1231

**Pull request closed without merging**
