### PR TITLE
Update wercker.yml

### PR DESCRIPTION
**Pull request by skmp**
For some reason looks like the install-packages script is broken...

### CODE REVIEW

**Comment by skmp** [comment]
This looks like some issue w/ the docker base image to me

**Comment by skmp** [comment]
Hah, nice idea... but build still failed :p

**Comment by skmp** [comment]
That last one seems to have nailed it. Interestingly, my similar attempt (update & co, but still using the pre-defined install deps step) failed. Hum. Wheeeee I guess :D

**Comment by Holzhaus** [comment]
Maybe it was the `clean`? I suppose that whole error was due to some crazy caching issue.

**Comment by skmp** [comment]
Can you make a clean PR just for it and merge it?

**Comment by Holzhaus** [comment]
Done.

**Pull request closed without merging**
